In [15]:
!pip install bertopic sentence-transformers umap-learn hdbscan

Collecting bertopic
  Downloading bertopic-0.17.4-py3-none-any.whl.metadata (24 kB)
Collecting sentence-transformers
  Downloading sentence_transformers-5.3.0-py3-none-any.whl.metadata (16 kB)
Collecting umap-learn
  Downloading umap_learn-0.5.11-py3-none-any.whl.metadata (26 kB)
Collecting hdbscan
  Downloading hdbscan-0.8.41.tar.gz (7.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.1/7.1 MB 95.3 MB/s  0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: numpy>=1.20.0 in /opt/python/lib/python3.13/site-packages (from bertopic) (2.4.2)
Requirement already satisfied: pandas>=1.1.5 in /opt/python/lib/python3.13/site-packages (from bertopic) (3.0.1)
Collecting plotly>=4.7.0 (from bertopic)
  Downloading plotly-6.6.0-py3-none-any.whl.metadata (8.5 kB)
Collecting scikit-learn>=1.0 (from bertopic)
  Downloading scikit_learn-1.8.0-cp313-cp313-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (11 kB)
Collecting tqdm>=4.41.1 (from bertopic)
  Downloading tqdm-4.67.3-py3-none-any.whl.metadata (57 kB)
Collecting llvmlite>0.36.0 (from bertopic)
  Downloading llvmlite-0.46.0-cp313-cp313-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (5.0 kB)
Collecting transformers<6.0.0,>=4.41.0 (from sentence-transformers)
  Downloading transformers-5.3.0-py3-none-any.whl.metadata (32 kB)
Collecting huggingface-hub>=0.20.0 (from sentence-transformers)
  Downloading huggingface_hub-1.7.2-py3-none-any.whl.metadata (13 kB)
Requirement already satisfied: torch>=1.11.0 in /opt/python/lib/python3.13/site-packages (from sentence-transformers) (2.10.0)
Collecting scipy (from sentence-transformers)
  Downloading scipy-1.17.1-cp313-cp313-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (62 kB)
Requirement already satisfied: typing_extensions>=4.5.0 in /opt/python/lib/python3.13/site-packages (from sentence-transformers) (4.15.0)
Requirement already satisfied: packaging>=20.0 in /opt/python/lib/python3.13/site-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (26.0)
Collecting pyyaml>=5.1 (from transformers<6.0.0,>=4.41.0->sentence-transformers)
  Downloading pyyaml-6.0.3-cp313-cp313-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (2.4 kB)
Collecting regex!=2019.12.17 (from transformers<6.0.0,>=4.41.0->sentence-transformers)
  Downloading regex-2026.2.28-cp313-cp313-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (40 kB)
Collecting tokenizers<=0.23.0,>=0.22.0 (from transformers<6.0.0,>=4.41.0->sentence-transformers)
  Downloading tokenizers-0.22.2-cp39-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (7.3 kB)
Collecting typer (from transformers<6.0.0,>=4.41.0->sentence-transformers)
  Downloading typer-0.24.1-py3-none-any.whl.metadata (16 kB)
Collecting safetensors>=0.4.3 (from transformers<6.0.0,>=4.41.0->sentence-transformers)
  Downloading safetensors-0.7.0-cp38-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (4.1 kB)
Requirement already satisfied: filelock>=3.10.0 in /opt/python/lib/python3.13/site-packages (from huggingface-hub>=0.20.0->sentence-transformers) (3.25.0)
Requirement already satisfied: fsspec>=2023.5.0 in /opt/python/lib/python3.13/site-packages (from huggingface-hub>=0.20.0->sentence-transformers) (2026.2.0)
Collecting hf-xet<2.0.0,>=1.4.2 (from huggingface-hub>=0.20.0->sentence-transformers)
  Downloading hf_xet-1.4.2-cp37-abi3-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (4.9 kB)
Collecting httpx<1,>=0.23.0 (from huggingface-hub>=0.20.0->sentence-transformers)
  Downloading httpx-0.28.1-py3-none-any.whl.metadata (7.1 kB)
Collecting anyio (from httpx<1,>=0.23.0->huggingface-hub>=0.20.0->sentence-transformers)
  Downloading anyio-4.12.1-py3-none-any.whl.metadata (4.3 kB)
Requirement already satisfied: certifi in /opt/python/lib/python3.13/site-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.20.0->sentence-transformers) (2026.2.25)
Collecting httpcore==1.* (from httpx<1,>=0.23.0->huggingface-hub>=0.20.0->sentence-transformers)
  Downloading httpcore-1.0.9-py3-none-any.whl.metadata (21 kB)
Requirement already satisfied: idna in /opt/python/lib/python3.13/site-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.20.0->sentence-transformers) (3.11)
Collecting h11>=0.16 (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub>=0.20.0->sentence-transformers)
  Downloading h11-0.16.0-py3-none-any.whl.metadata (8.3 kB)
Collecting numba>=0.51.2 (from umap-learn)
  Downloading numba-0.64.0-cp313-cp313-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (2.9 kB)
Collecting pynndescent>=0.5 (from umap-learn)
  Downloading pynndescent-0.6.0-py3-none-any.whl.metadata (6.9 kB)
Collecting joblib>=1.0 (from hdbscan)
  Downloading joblib-1.5.3-py3-none-any.whl.metadata (5.5 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in /opt/python/lib/python3.13/site-packages (from pandas>=1.1.5->bertopic) (2.9.0.post0)
Collecting narwhals>=1.15.1 (from plotly>=4.7.0->bertopic)
  Downloading narwhals-2.18.0-py3-none-any.whl.metadata (14 kB)
Requirement already satisfied: six>=1.5 in /opt/python/lib/python3.13/site-packages (from python-dateutil>=2.8.2->pandas>=1.1.5->bertopic) (1.17.0)
Collecting threadpoolctl>=3.2.0 (from scikit-learn>=1.0->bertopic)
  Downloading threadpoolctl-3.6.0-py3-none-any.whl.metadata (13 kB)
Requirement already satisfied: setuptools in /opt/python/lib/python3.13/site-packages (from torch>=1.11.0->sentence-transformers) (82.0.0)
Requirement already satisfied: sympy>=1.13.3 in /opt/python/lib/python3.13/site-packages (from torch>=1.11.0->sentence-transformers) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /opt/python/lib/python3.13/site-packages (from torch>=1.11.0->sentence-transformers) (3.6.1)
Requirement already satisfied: jinja2 in /opt/python/lib/python3.13/site-packages (from torch>=1.11.0->sentence-transformers) (3.1.6)
Requirement already satisfied: cuda-bindings==12.9.4 in /opt/python/lib/python3.13/site-packages (from torch>=1.11.0->sentence-transformers) (12.9.4)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.8.93 in /opt/python/lib/python3.13/site-packages (from torch>=1.11.0->sentence-transformers) (12.8.93)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.8.90 in /opt/python/lib/python3.13/site-packages (from torch>=1.11.0->sentence-transformers) (12.8.90)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.8.90 in /opt/python/lib/python3.13/site-packages (from torch>=1.11.0->sentence-transformers) (12.8.90)
Requirement already satisfied: nvidia-cudnn-cu12==9.10.2.21 in /opt/python/lib/python3.13/site-packages (from torch>=1.11.0->sentence-transformers) (9.10.2.21)
Requirement already satisfied: nvidia-cublas-cu12==12.8.4.1 in /opt/python/lib/python3.13/site-packages (from torch>=1.11.0->sentence-transformers) (12.8.4.1)
Requirement already satisfied: nvidia-cufft-cu12==11.3.3.83 in /opt/python/lib/python3.13/site-packages (from torch>=1.11.0->sentence-transformers) (11.3.3.83)
Requirement already satisfied: nvidia-curand-cu12==10.3.9.90 in /opt/python/lib/python3.13/site-packages (from torch>=1.11.0->sentence-transformers) (10.3.9.90)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.3.90 in /opt/python/lib/python3.13/site-packages (from torch>=1.11.0->sentence-transformers) (11.7.3.90)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.8.93 in /opt/python/lib/python3.13/site-packages (from torch>=1.11.0->sentence-transformers) (12.5.8.93)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /opt/python/lib/python3.13/site-packages (from torch>=1.11.0->sentence-transformers) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.27.5 in /opt/python/lib/python3.13/site-packages (from torch>=1.11.0->sentence-transformers) (2.27.5)
Requirement already satisfied: nvidia-nvshmem-cu12==3.4.5 in /opt/python/lib/python3.13/site-packages (from torch>=1.11.0->sentence-transformers) (3.4.5)
Requirement already satisfied: nvidia-nvtx-cu12==12.8.90 in /opt/python/lib/python3.13/site-packages (from torch>=1.11.0->sentence-transformers) (12.8.90)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.8.93 in /opt/python/lib/python3.13/site-packages (from torch>=1.11.0->sentence-transformers) (12.8.93)
Requirement already satisfied: nvidia-cufile-cu12==1.13.1.3 in /opt/python/lib/python3.13/site-packages (from torch>=1.11.0->sentence-transformers) (1.13.1.3)
Requirement already satisfied: triton==3.6.0 in /opt/python/lib/python3.13/site-packages (from torch>=1.11.0->sentence-transformers) (3.6.0)
Requirement already satisfied: cuda-pathfinder~=1.1 in /opt/python/lib/python3.13/site-packages (from cuda-bindings==12.9.4->torch>=1.11.0->sentence-transformers) (1.4.1)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /opt/python/lib/python3.13/site-packages (from sympy>=1.13.3->torch>=1.11.0->sentence-transformers) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /opt/python/lib/python3.13/site-packages (from jinja2->torch>=1.11.0->sentence-transformers) (3.0.3)
Collecting click>=8.2.1 (from typer->transformers<6.0.0,>=4.41.0->sentence-transformers)
  Downloading click-8.3.1-py3-none-any.whl.metadata (2.6 kB)
Collecting shellingham>=1.3.0 (from typer->transformers<6.0.0,>=4.41.0->sentence-transformers)
  Downloading shellingham-1.5.4-py2.py3-none-any.whl.metadata (3.5 kB)
Collecting rich>=12.3.0 (from typer->transformers<6.0.0,>=4.41.0->sentence-transformers)
  Downloading rich-14.3.3-py3-none-any.whl.metadata (18 kB)
Collecting annotated-doc>=0.0.2 (from typer->transformers<6.0.0,>=4.41.0->sentence-transformers)
  Downloading annotated_doc-0.0.4-py3-none-any.whl.metadata (6.6 kB)
Collecting markdown-it-py>=2.2.0 (from rich>=12.3.0->typer->transformers<6.0.0,>=4.41.0->sentence-transformers)
  Downloading markdown_it_py-4.0.0-py3-none-any.whl.metadata (7.3 kB)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /opt/python/lib/python3.13/site-packages (from rich>=12.3.0->typer->transformers<6.0.0,>=4.41.0->sentence-transformers) (2.19.2)
Collecting mdurl~=0.1 (from markdown-it-py>=2.2.0->rich>=12.3.0->typer->transformers<6.0.0,>=4.41.0->sentence-transformers)
  Downloading mdurl-0.1.2-py3-none-any.whl.metadata (1.6 kB)
Downloading bertopic-0.17.4-py3-none-any.whl (154 kB)
Downloading sentence_transformers-5.3.0-py3-none-any.whl (512 kB)
Downloading transformers-5.3.0-py3-none-any.whl (10.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.7/10.7 MB 93.9 MB/s  0:00:00
Downloading huggingface_hub-1.7.2-py3-none-any.whl (618 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 618.0/618.0 kB 59.9 MB/s  0:00:00
Downloading hf_xet-1.4.2-cp37-abi3-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (4.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.2/4.2 MB 84.3 MB/s  0:00:00
Downloading httpx-0.28.1-py3-none-any.whl (73 kB)
Downloading httpcore-1.0.9-py3-none-any.whl (78 kB)
Downloading tokenizers-0.22.2-cp39-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (3.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.3/3.3 MB 86.1 MB/s  0:00:00
Downloading umap_learn-0.5.11-py3-none-any.whl (90 kB)
Downloading h11-0.16.0-py3-none-any.whl (37 kB)
Downloading joblib-1.5.3-py3-none-any.whl (309 kB)
Downloading llvmlite-0.46.0-cp313-cp313-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (56.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 56.3/56.3 MB 93.0 MB/s  0:00:00m eta 0:00:01
Downloading numba-0.64.0-cp313-cp313-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (3.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.8/3.8 MB 84.1 MB/s  0:00:00
Downloading plotly-6.6.0-py3-none-any.whl (9.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.9/9.9 MB 90.5 MB/s  0:00:00
Downloading narwhals-2.18.0-py3-none-any.whl (444 kB)
Downloading pynndescent-0.6.0-py3-none-any.whl (73 kB)
Downloading pyyaml-6.0.3-cp313-cp313-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (801 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 801.6/801.6 kB 64.7 MB/s  0:00:00
Downloading regex-2026.2.28-cp313-cp313-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (802 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 802.1/802.1 kB 67.9 MB/s  0:00:00
Downloading safetensors-0.7.0-cp38-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (507 kB)
Downloading scikit_learn-1.8.0-cp313-cp313-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (8.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.9/8.9 MB 94.3 MB/s  0:00:00
Downloading scipy-1.17.1-cp313-cp313-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (35.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 35.2/35.2 MB 95.1 MB/s  0:00:00m eta 0:00:01
Downloading threadpoolctl-3.6.0-py3-none-any.whl (18 kB)
Downloading tqdm-4.67.3-py3-none-any.whl (78 kB)
Downloading anyio-4.12.1-py3-none-any.whl (113 kB)
Downloading typer-0.24.1-py3-none-any.whl (56 kB)
Downloading annotated_doc-0.0.4-py3-none-any.whl (5.3 kB)
Downloading click-8.3.1-py3-none-any.whl (108 kB)
Downloading rich-14.3.3-py3-none-any.whl (310 kB)
Downloading markdown_it_py-4.0.0-py3-none-any.whl (87 kB)
Downloading mdurl-0.1.2-py3-none-any.whl (10.0 kB)
Downloading shellingham-1.5.4-py2.py3-none-any.whl (9.8 kB)
Building wheels for collected packages: hdbscan
  Building wheel for hdbscan (pyproject.toml) ... done
  Created wheel for hdbscan: filename=hdbscan-0.8.41-cp313-cp313-linux_x86_64.whl size=4396451 sha256=39fe601268d3653bafda1efaa50bfd920978ca53a95602709ca75bc075d878f0
  Stored in directory: /home/onyxia/.cache/pip/wheels/c8/bc/55/6d2928daed92cff0ff2b4c592c9c09546c3168ba0faeb610df
Successfully built hdbscan
Installing collected packages: tqdm, threadpoolctl, shellingham, scipy, safetensors, regex, pyyaml, narwhals, mdurl, llvmlite, joblib, hf-xet, h11, click, anyio, annotated-doc, scikit-learn, plotly, numba, markdown-it-py, httpcore, rich, pynndescent, httpx, hdbscan, umap-learn, typer, huggingface-hub, tokenizers, transformers, sentence-transformers, bertopic
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 32/32 [bertopic]/32 [bertopic]transformers]
Successfully installed annotated-doc-0.0.4 anyio-4.12.1 bertopic-0.17.4 click-8.3.1 h11-0.16.0 hdbscan-0.8.41 hf-xet-1.4.2 httpcore-1.0.9 httpx-0.28.1 huggingface-hub-1.7.2 joblib-1.5.3 llvmlite-0.46.0 markdown-it-py-4.0.0 mdurl-0.1.2 narwhals-2.18.0 numba-0.64.0 plotly-6.6.0 pynndescent-0.6.0 pyyaml-6.0.3 regex-2026.2.28 rich-14.3.3 safetensors-0.7.0 scikit-learn-1.8.0 scipy-1.17.1 sentence-transformers-5.3.0 shellingham-1.5.4 threadpoolctl-3.6.0 tokenizers-0.22.2 tqdm-4.67.3 transformers-5.3.0 typer-0.24.1 umap-learn-0.5.11

In [ ]:
# Si hdbscan marche pas on peut utiliser ça

from sklearn.cluster import HDBSCAN
from bertopic.cluster import BaseCluster
"""
class SklearnHDBSCAN(BaseCluster):
    def __init__(self, *args, **kwargs):
        self.model = HDBSCAN(*args, **kwargs)
    
    def fit(self, X):
        self.model.fit(X)
        self.labels_ = self.model.labels_
        return self
    
    def fit_predict(self, X):
        self.labels_ = self.model.fit_predict(X)
        return self.labels_
hdbscan_model = SklearnHDBSCAN(
    min_cluster_size=50,      # bigger = fewer, larger topics
    min_samples=10,            # higher = more conservative clustering
    cluster_selection_epsilon=0.1,  # merge nearby clusters
    cluster_selection_method='leaf' # fewer, more specific clusters
)
"""

Récupération des fichiers CSV

In [ ]:
import pandas as pd
import os
import s3fs



fs = s3fs.S3FileSystem(
    client_kwargs={'endpoint_url': 'https://'+'minio.lab.sspcloud.fr'},
    key = os.environ["AWS_ACCESS_KEY_ID"], 
    secret = os.environ["AWS_SECRET_ACCESS_KEY"], 
    token = os.environ["AWS_SESSION_TOKEN"])

s3_folder = "s3://lab/PESSD/csv/patin_art"

files = fs.glob(f"{s3_folder}/*.csv")

for file in files:
    fs.get(file, "data/"+(file.removeprefix("lab/PESSD/csv/patin_art/")))

In [11]:
df = pd.DataFrame()
for file in os.listdir("data") : 
    temp = pd.read_csv("data/"+file)
    df = pd.concat([df,temp])

Nettoyage de la data

In [12]:
import re

# Removing music and noise (only technical commentary)
df = df[(df["main_g"]=="female")|(df["main_g"]=="male")]

# text to sentences
df["text"] = df["text"].apply(lambda x : x.split(". "))
df = df.explode("text")

# Removes all words with capitals
# A éviter car détruit du sens

#df["text"] = df["text"].apply(lambda x : re.sub(r"\s*[A-Z]\w*\s*", " ", x).strip())

On ajoute les métadonnées

In [13]:
df["ID"] = df["audio_file"].str.replace("_wav.wav","")
df = df.merge(pd.read_csv("metadata.csv"), on="ID")

In [14]:
df

,start,stop,text,main_speaker,main_g,audio_file,ID,g_ath
0,7.08,17.88,les ...,SPEAKER_02,female,ELC_wav.wav,ELC,M
1,7.08,17.88,Les mamansament font lui,SPEAKER_02,female,ELC_wav.wav,ELC,M
2,18.04,4.98,des,SPEAKER_00,female,ELC_wav.wav,ELC,M
3,19.16,52.68,iniciants,SPEAKER_02,female,ELC_wav.wav,ELC,M
4,19.16,52.68,Ils n'entraînent pas et n'en peuvent pas,SPEAKER_02,female,ELC_wav.wav,ELC,M
...,...,...,...,...,...,...,...,...
7855,1916.16,1949.48,Et passer le cut,SPEAKER_04,female,DR2_wav.wav,DR2,F
7856,1916.16,1949.48,"Merci Nathalie et Péchala, merci Annick Dumont",SPEAKER_04,female,DR2_wav.wav,DR2,F
7857,1916.16,1949.48,"Merci Marie-Christine, Marie",SPEAKER_04,female,DR2_wav.wav,DR2,F
7858,1916.16,1949.48,On se retrouve demain pour de nouvelles aventures,SPEAKER_04,female,DR2_wav.wav,DR2,F
7859,1916.16,1949.48,Merci à tous.,SPEAKER_04,female,DR2_wav.wav,DR2,F

In [19]:
from bertopic import BERTopic
from sentence_transformers import SentenceTransformer
from sklearn.feature_extraction.text import CountVectorizer
from umap import UMAP
import hdbscan

# Stopwords list
STOPWORDS = [x.strip() for x in open('stopwords.txt').readlines()]

# Docs 
docs = df["text"]

# Vectorizer for topic representation
vectorizer_model = CountVectorizer(
    stop_words=STOPWORDS,
    ngram_range=(1,2),
    min_df=2,
    token_pattern=r"\b(?!\w*[A-Z])\w+\b" # theoreticaly removes words with capital letters once embeddings are done
)

# To control for number and size of clusters
hdbscan_model = hdbscan.HDBSCAN(
    min_cluster_size=50,      # bigger = fewer, larger topics
    min_samples=10,            # higher = more conservative clustering
    cluster_selection_epsilon=0.1,  # merge nearby clusters
    cluster_selection_method='leaf', # fewer, more specific clusters
    prediction_data=True # important !!
)

# Load CamemBERT embedding model
embedding_model = SentenceTransformer("dangvantuan/sentence-camembert-base", device="cuda") # remove device if CPU

# Influence choice of themes
seed =  [
["émotion","larme","ému","joie","tristesse"],
["famille","parents","ami", "personnel", "conjoint"]]

# Build BERTopic model
topic_model = BERTopic(
    embedding_model=embedding_model,
    vectorizer_model=vectorizer_model,
    hdbscan_model=hdbscan_model,
    language="french",
    calculate_probabilities=True,
    verbose=True,
    seed_topic_list=seed    
)

# Fit the model
topics, probs = topic_model.fit_transform(docs)

# Show discovered topics
print(topic_model.get_topic_info())

# Visualize topics
#topic_model.visualize_topics()

# Visualize topic hierarchy
topic_model.visualize_hierarchy()

#keybertopic, extrait phrases saillantes
#tester lda
#virer phrases nulles et refaire tourner
#pas virer -1 sauf si faible échantillon et checker
#checker si semi-superviser pour trouver thèmes

Loading weights: 100%|██████████| 199/199 [00:00<00:00, 2882.61it/s]
CamembertModel LOAD REPORT from: dangvantuan/sentence-camembert-base
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
2026-03-22 15:42:53,942 - BERTopic - Embedding - Transforming documents to embeddings.
Batches: 100%|██████████| 246/246 [00:12<00:00, 20.28it/s]
2026-03-22 15:43:06,156 - BERTopic - Embedding - Completed ✓
2026-03-22 15:43:06,157 - BERTopic - Guided - Find embeddings highly related to seeded topics.
Batches: 100%|██████████| 1/1 [00:00<00:00, 100.88it/s]
2026-03-22 15:43:06,233 - BERTopic - Guided - Completed ✓
2026-03-22 15:43:06,318 - BERTopic - Dimensionality - Fitting the dimensionality reduction algorithm
2026-03-22 15:43:45,850 - BERTopic - Dimensionality - Completed ✓
2026-03-22 15:43:45,852 - BERTopic - Cluster - Start clustering the reduced embeddings
2026-03-22 15:43:46,926 - BERTopic - Cluster - Completed ✓
2026-03-22 15:43:46,940 - BERTopic - Representation - Fine-tuning topics using representation models.
2026-03-22 15:43:47,146 - BERTopic - Representation - Completed ✓

    Topic  Count                                             Name  \
0      -1   3188          -1_programme_vraiment_points_évidemment
1       0    307               0_musique_chorégraphie_danse_choix
2       1    305            1_incroyable_parfait_magnifique_super
3       2    282                 2_couple_couples_canadiens_japon
4       3    281          3_patinage_patineur_patineurs_patineuse
5       4    254                          4_aïe_aïe aïe_joie_émue
6       5    204                      5_saut_sauts_lutz_quadruple
7       6    178       6_provisoire_place_place provisoire_podium
8       7    163                      7_sûre_regardons_voir_verra
9       8    152            8_niveau_technique_4_niveau technique
10      9    149           9_europe_monde_champion_champion monde
11     10    127             10_glace_danse glace_danse_patinoire
12     11    122                 11_triple_petit_saut_combinaison
13     12    120              12_parfait_attention_maxime_imagine
14     13    118     13_bras_position_arrière_changement position
15     14    105                      14_note_scorez_notes_monter
16     15    105                      15_triple_boucle_piqué_flip
17     16    103      16_olympiques_jeux olympiques_jeux_médaille
18     17    100            17_nathalie_pensé_annick_annick pensé
19     18     92    18_pirouettes_pirouette_acrobatique_acrobatie
20     19     88    19_programme_libre_programmes_programme court
21     20     87              20_axel_triple axel_rotation_triple
22     21     87              21_oui oui_oui_oui complètement_sûr
23     22     86                      22_canada_france_place_tête
24     23     82                           23_juges_bonus_malus_5
25     24     78           24_laurence_guillaume_cizeron_fournier
26     25     78             25_vidéo_arrivée_appels vidéo_appels
27     26     72  26_entraîne_entraînement_entraîneurs_entraîneur
28     27     68       27_serré_pression_serré serré_prendre tête
29     28     64              28_unis_etats unis_etats_états unis
30     29     63        29_chute_déduction_chutes_point déduction
31     30     60           30_compétition_épreuve_team_team event
32     31     58                   31_tours_demi_tour_tours tours
33     32     57            32_énergie_élégance_résilience_combat
34     33     56                               33_55_mesure_46_62
35     34     55                      34_ok_bonsoir_oui_attention
36     35     55      35_score_meilleur score_score saison_saison
37     36     54           36_attention_impression_inspiration_ex
38     37     54        37_sakamoto_kaori_kaori sakamoto_kajiyama
39     38     53    38_artistique_artistiques_artistiquement_plan
40     39     50        39_annick_gauchère_hier entraînement_hier

                                       Representation  \
0   [programme, vraiment, points, évidemment, fran...
1   [musique, chorégraphie, danse, choix, film, pa...
2   [incroyable, parfait, magnifique, super, adore...
3   [couple, couples, canadiens, japon, canada, en...
4   [patinage, patineur, patineurs, patineuse, pat...
5   [aïe, aïe aïe, joie, émue, sourire, déçue, con...
6   [saut, sauts, lutz, quadruple, lancé, triple, ...
7   [provisoire, place, place provisoire, podium, ...
8   [sûre, regardons, voir, verra, montrer, suspen...
9   [niveau, technique, 4, niveau technique, nivea...
10  [europe, monde, champion, champion monde, cham...
11  [glace, danse glace, danse, patinoire, feu, pa...
12  [triple, petit, saut, combinaison, points, sau...
13  [parfait, attention, maxime, imagine, suspense...
14  [bras, position, arrière, changement position,...
15  [note, scorez, notes, monter, scoret, 2ème not...
16  [triple, boucle, piqué, flip, triple flip, tri...
17  [olympiques, jeux olympiques, jeux, médaille, ...
18  [nathalie, pensé, annick, annick pensé, pensez...
19  [pirouettes, pirouette, acrobatique, acrobatie...
20  [programme, libre, programmes, programme court...
21  [axel, triple axel, rotation, triple, double a...
22  [oui oui, oui, oui complètement, sûr, oui sûr,...
23  [canada, france, place, tête, instant, france ...
24  [juges, bonus, malus, 5, 5 points, bonus malus...
25  [laurence, guillaume, cizeron, fournier, guill...
26  [vidéo, arrivée, appels vidéo, appels, arrivée...
27  [entraîne, entraînement, entraîneurs, entraîne...
28  [serré, pression, serré serré, prendre tête, t...
29  [unis, etats unis, etats, états unis, états, t...
30  [chute, déduction, chutes, point déduction, pe...
31  [compétition, épreuve, team, team event, event...
32  [tours, demi, tour, tours tours, tours demi, t...
33  [énergie, élégance, résilience, combat, dégage...
34  [55, mesure, 46, 62, 102, 102 55, 64, 92, 70, ...
35  [ok, bonsoir, oui, attention, oui thème, 8, fa...
36  [score, meilleur score, score saison, saison, ...
37  [attention, impression, inspiration, ex, parla...
38  [sakamoto, kaori, kaori sakamoto, kajiyama, yu...
39  [artistique, artistiques, artistiquement, plan...
40  [annick, gauchère, hier entraînement, hier, er...

                                  Representative_Docs
0   [Alors le podium, enfin pour l'instant le clas...
1   [Tout est en musique, Et c'est en musique, La ...
2   [C'est incroyable, C'est incroyable., C'est ab...
3   [Et voici le couple tant redouté, C'est un cou...
4   [Mais encore une fois, c'est un mythe et sans ...
5   [Aïe aïe aïe, K.O, Aïe aïe aïe c'est bas c'est...
6   [L'autre saut lancé., Ce saut lancé, c'est une...
7   [Dixième place provisoire pour Sélévko., Trois...
8   [J'en suis sûre, Et là, je ne suis pas sûre de...
9   [Annick, au niveau de la technique, Je pense q...
10  [L'objectif, c'est un podium, Ce couple est ch...
11  [en danse sur glace, Alors voilà, après la dan...
12  [et là on le voit au ralenti le même saut vous...
13  [Parfait., Anic Tiquet sur une arrivée du.., A...
14  [Changement de position, il lâche un bras, Cha...
15  [Il est bien au-dessus des autres sur la deuxi...
16  [C'est un triple boucle., Et quadruple boucle ...
17  [dans les chistes des Jeux Olympiques, Ils par...
18  [Merci Nathalie, C'est ça, à peu près, Nathali...
19  [Annick, les pirouettes..., Je vous ai vu surs...
20  [Voilà un très beau programme., Et à Dan, il y...
21  [Deuxième triple axel, Le triple axel., Une ém...
22  [Ah oui oui, on sait que.., Oui, oui, tout à f...
23  [Va-t-on rester en tête de cette compétition a...
24  [Parce que chaque élément, selon le fait qu'il...
25  [Derrière, Guillaume Cizeron, Laurence Fournie...
26  [Il y a beaucoup d'appels vidéo, quelques appe...
27  [Elle s'entraîne à Vaujanie avec Florent Amodi...
28  [Très très serré, Ah là là, ça va être serré, ...
29  [L'entrée en lice des Etats-Unis, 2e, les Etat...
30  [Il y a en plus une chute, Et il y a pas de ch...
31  [Pas que pour cette compétition d'ailleurs., E...
32  [Un tour, deux tours, trois tours, On peut fai...
33  [Il y a une telle énergie de l'un comme de l'a...
34  [parce que je peux vous assurer qu'entre 102, ...
35                                       [OK, OK, OK]
36  [Le meilleur score de la saison eux aussi comm...
37  [Voilà, c'est l'élément dont je vous parlais t...
38  [Et la dernière a passé, Kaori Sakamoto, le Ja...
39  [Très artistique, C'est la douaillaine du bâti...
40  [Une superwoman Annick, Alors Annick, avec vot...

On regroupe les phrases par topic

In [21]:
tp = pd.DataFrame({
    "text": docs,
    "topic": topics,
    "topic_prob": probs.max(axis=1)  # max probability per text
})
tp["topic"].value_counts()

topic
-1     3188
 0      307
 1      305
 2      282
 3      281
 4      254
 5      204
 6      178
 7      163
 8      152
 9      149
 10     127
 11     122
 12     120
 13     118
 15     105
 14     105
 16     103
 17     100
 18      92
 19      88
 20      87
 21      87
 22      86
 23      82
 25      78
 24      78
 26      72
 27      68
 28      64
 29      63
 30      60
 31      58
 32      57
 33      56
 35      55
 34      55
 36      54
 37      54
 38      53
 39      50
Name: count, dtype: int64

In [22]:
df = df.merge(tp, on="text")
df

,start,stop,text,main_speaker,main_g,audio_file,ID,g_ath,topic,topic_prob
0,7.08,17.88,les ...,SPEAKER_02,female,ELC_wav.wav,ELC,M,-1,0.052528
1,7.08,17.88,Les mamansament font lui,SPEAKER_02,female,ELC_wav.wav,ELC,M,2,1.000000
2,18.04,4.98,des,SPEAKER_00,female,ELC_wav.wav,ELC,M,-1,0.048393
3,19.16,52.68,iniciants,SPEAKER_02,female,ELC_wav.wav,ELC,M,12,1.000000
4,19.16,52.68,Ils n'entraînent pas et n'en peuvent pas,SPEAKER_02,female,ELC_wav.wav,ELC,M,26,1.000000
...,...,...,...,...,...,...,...,...,...,...
15025,1916.16,1949.48,Et passer le cut,SPEAKER_04,female,DR2_wav.wav,DR2,F,-1,0.049630
15026,1916.16,1949.48,"Merci Nathalie et Péchala, merci Annick Dumont",SPEAKER_04,female,DR2_wav.wav,DR2,F,17,1.000000
15027,1916.16,1949.48,"Merci Marie-Christine, Marie",SPEAKER_04,female,DR2_wav.wav,DR2,F,2,0.144693
15028,1916.16,1949.48,On se retrouve demain pour de nouvelles aventures,SPEAKER_04,female,DR2_wav.wav,DR2,F,-1,0.022534
15029,1916.16,1949.48,Merci à tous.,SPEAKER_04,female,DR2_wav.wav,DR2,F,-1,0.060055

In [23]:
# Sentences of topic i

for k in df[df["topic"]==1]["text"] : 
    print(k)

C'est ça qui est hyper impressionnant
Tout était incroyable et fantastique.
Jamais de la vie
Il est super
La sensation, elle doit être incroyable
Et brillant
C'était un truc pour...
Triple bout, parfait.
Et c'est très bien
C'est très très rare ce que l'on vient de voir
Ça aussi, c'est incroyable
C'est très rare
Mais c'est quand même exceptionnel.
Ils arrivent vraiment à nous embarquer dans leur histoire.
J'adore cette image arrêtée, c'est beau
Je l'adore, c'est super.
Le score, incroyable
Même là, c'est limite.
Très souvent, tout cas Daniel.
Parfois ça ne passe pas, mais quand ça passe, qu'est-ce que c'est bon
C'est extra
Ça c'est super
No, I wish the sea wonder
C'est extraordinaire
C'est extraordinaire
Moi, j'ai adoré
C'était une pure merveille
Tout est subtil
C'est absolument divin
J'ai adoré
Donc ça serait extraordinaire
Sur le reste c'est magnifique
Mais elle va être excellente
Alors moi je l'adore à elle
portée là, qui est magnifique
Niveau 4 oui, mais surtout c'est original, c'est propre, la sortie est très soignée
Ils ont été très généreux
Je peux même pas vous dire tellement c'est..
Il se souvient de son histoire, sa liberté artistique, mais sa liberté personnelle quand il décide de partir à l'ouest
Qui fuite son pays, qui laisse sa maman...
Il n'y a rien à dire, ils sont merveilleux, ils sont extraordinaires.
Ça, franchement, il y a une recherche incroyable
Il est unique, oui
Je suis un petit peu moins transportée par le thème
Ce sont des vies qui sont assez intense, assez particulières.
C'était une manière de dire merci
C'est vraiment une superbe histoire
Maman, c'est magnifique
Alors, je les adore
C'est l'un de leurs plus belles créations
Un grand merci moi j'étais totalement fan de cette nuit étoilée de Van Gogh
Vous avez vu ce qui est arrivé aux Anglais ? Non mais c'est bien, ça a été qu'on s'emballe.
Bravo ! C'est une terrible belle histoire
Ah bah oui, c'est extraordinaire
C'est peut-être pas plus, plus, plus que parfait, mais c'est tellement parfait
Ce programme vous transporte dans un monde de poésie et de volupté.
Regardez ça, c'est exceptionnel.
Et c'est mérité
Ça serait mérité
Ils sont rentrés dans le terme des légendes
Ah dis donc, quelle histoire, quelle aventure.
Quelle aventure
Wow, bravo, un grand bravo à eux et à toute l'équipe.
Non, ça reste relativement rare
Ils ont été fabuleux
Il y avait absolument tout
Voilà, I'm too sexy, vous l'avez entendu
Ouais, c'est planté
Oui, franchement, super
C'est trop mignon de les voir grandir et réussir cette belle carrière
Moi, je les ai beaucoup aimés
Ça a toujours été le cas
Même si on adore
Et ça leur va très bien
Ça lui va magnifiquement bien
Elle est absolument sublime
Vous allez l'avoir, les voir, c'est extrêmement expressif
Ils ont fait Beyoncé aussi, ça a été extrêmement marquant.
Elle est divine
Everybody and that's the way I like it, the back street
Elle est super.
C'est vraiment très beau
C'est une plus en merveille, Aïdicat
C'est magnifique
Et c'est beau
mais vraiment il la salue beaucoup plus chaleureusement que l'italienne
Elle est évidemment extrêmement bien remerciée par le public qui la soutient et qui attend à chaque fois cet élément
Chapeau, chapeau, bravo !
Elle est capitale, sympathique, plus, plus, plus
Elle est captivante, elle nous amène
Elle est remarquable
C'est mignon
Ce qui est incroyable, c'est..
Donc magique, magnifique
J'adore.
Ça c'est tout le côté positif
Oui, oui, absolument
Hop, vous l'avez vu le petit ballon là ? Parfait
Je l'apprécie énormément
Je ne sais pas ce que tu en penses, Annick, mais c'est quand même surprenant à ce niveau-là.
Wouah ! C'est..
Et c'est surprenant la part d'un arbre neuf.
On sait que c'est le moment qui vous qui vous transcende.
Ah super.
Vous allez voir, c'est merveilleux
Il y avait tout, tout ! C'était magique, magnifique
Parce que là, regardez comme c'est net
Qui est surtout hyper respectueux et c'est vraiment un...
C'est incroyable.
Après, je vous raconterai une histoire
Oh là là là là là là, ça c'était très très très bon
Oh là, c'est mignon ! L'émotion des coaches, faut s'y penser.
Il est grandiose.
Quatre-flippes, superbe
Regardez, regardez, ça c'est exceptionnel
C'est parfait ça
J'ai beaucoup aimé leur proposition
J'ai beaucoup aimé leur proposition
Nathalie, ça vous a enchanté beaucoup.
Ça donne un parfum
Ça donne un parfum
Ça donne un parfum
Ça donne un parfum à la Grande-Bretagne
Je trouve que c'est une très belle entière..
Je trouve que c'est une très belle entière..
63, bravo !
Bravo ! C'est super !
Pas vraiment bon du tout, hein, puisque..
Aie, aie, aie ! On sent une lumière
Le reste, mais je suis emballée, emballée, supportée, mais c'est un petit bijou
Mais non, mais non, je vais tout ! C'était sublime la descente
Mais non, mais non, je vais tout ! C'était sublime la descente
Pour moi, ils m'ont emballée sur la deuxième note
Pour moi, ils m'ont emballée sur la deuxième note
C'est beau.
Splendide
Parce que c'est bon
Très très bien
C'était de toute beauté
que c'était rare aujourd'hui.
Oui, parce qu'elle a absolument tout
Oui, parce qu'elle a absolument tout
Non, absolument
Et alors ça, je peux vous dire que c'est pénalisé
C'est absolument parfait.
C'est absolument parfait.
Alors ? C'est mignon ça j'adore
Nathalie, elle vous a emballé
J'allais dire bluffé, mais non, parce qu'on sait de quoi Lauren est capable
Moi je suis pleine d'admiration
Bravo, bravo, je suis très fière d'elle.
Donc c'est extrêmement excitant
C'est juste merveilleux
Oui, parce qu'elle a absolument tout
Oui, parce qu'elle a absolument tout
Non absolument et c'est
Et alors ça je peux vous dire que c'est pénalisé
C'est absolument parfait.
C'est absolument parfait.
Alors ? Oh c'est mignon ça j'adore
Nathalie, elle vous a emballé.
J'allais dire bluffé, mais non, parce qu'on sait de quoi Lauryn est capable
Bravo, bravo, je suis très fière d'elle.
Oui, je pense comme nous tous, ça nous a emmené
Vous l'avez vu là, hein ? Un car, un bon bon car
Ça, ça nous cloue le bec
Ça, ça nous cloue le bec
C'est incroyable
C'est incroyable
C'est ce qu'elle a vécu pendant deux ans
Wouah ! Oh ! Qu'un seul mot magnifique ! Ce que l'on aime chez cette fille, ça peut dire majestueux aussi
Ah ça vous plait cette phrase, ça m'impressionne
Je serais très généreuse
Je serais très généreuse
Elle est dans une générosité
Oui, j'étais assez satisfaite de leurs prestations parce qu'on les sent toujours comme d'habitude très accrochés
Je veux vraiment que vous le regardiez parce que c'est un petit bijou.
C'est comme une bouteille.
C'est un élément unique
Et là, c'était beau.
Si, ça a l'air très rigolo
C'est très, très bien, vraiment
Le voile là, il est très très bon.
Voilà ce qui est parfait
Ça c'est bon, là c'est bon
Ludique et joyeux
Alors là, j'adore ces images, c'est tellement parfait
Tellement j'ai aimé.
C'était beau.
C'est tellement bien ça.
Et là, mesdames et messieurs, le grand moment, un des deux grands moments pour nous, nos Français
C'est admirable.
Je vous le disais, ça, c'est incroyable
Incroyable ce qu'il a pu
Regardez ça, c'est incroyable
Il a très bien interprété Daniel
En fait, moi, avant toute chose, je dis bravo
Musique douce
Il est incroyable
C'est absolument incroyable.
C'est absolument dingue, ce qui s'est passé
Depuis 10 ans, 15 ans, le contenu, c'est incroyable,
c'est effroyable
C'est un truc de dingue
Ce qu'on est en train de vivre, c'est un truc de dingue
On a vécu.
Et vraiment, toutes nos félicitations
Bravo, bravo, grand champion.
Vous savez, celui-ci, regardez, ça pique
Regardez cette merveille
C'est une petite merveille
C'est très intéressant
Je crois vraiment que le mot exceptionnel c'est vraiment de ça, de ce que l'on va vivre
Je veux dire, fanta..
Bon, fanta..
L'idée, ça va être juste extraordinaire
En fait, elle est très surprenante
Et ça lui va extrêmement bien
Mais c'est magnifique.
Tout est magnifique
Bravo, ça c'est vraiment..
Très fin, très délicat
C'est tellement subtil, tellement subtil.
On n'est pas brillantes brillantes.
En fait, tout est magnifique chez Monet.
Alice Alou vient de réaliser un truc exceptionnel
Et je pense que nous, on part avec elle dans son patinage et dans son histoire.
Vraiment, c'est un extraterrestre, mais que ça fait du bien, ce vent de fraîcheur
Elle est exceptionnelle, vous rappelez.
Elle a dit, je réécris ma vie, c'est incroyable
Je fais ce qui me plaît
Et puis, elle a même voyagé, elle a fait un super..
Franchement, bravo, bravo, bravo
Et ses cheveux, on raconte l'histoire de ses cheveux
Chaque année, j'adore
Elle est extraordinaire
Franchement génial.
Ben franchement, c'est réussi.
Non j'ai apprécié j'étais tellement tendue là pour le coup que j'ai du mal à
En tout cas c'est un phénomène
C'est extraordinaire
C'est extraordinaire
C'est juste incroyable ce qu'on a vécu et on avait eu des émotions de dingue
Mais moi j'ai envie de..
Mais le résultat est tellement parfait, il est tellement parfait ce résultat, il n'y a rien à dire.
Je trouve que c'est une très belle entière..
Je trouve que c'est une très belle entière..
C'est super.
Pas vraiment bon, même pas bon du tout
Et là, c'est merveilleux
Alleluia, alleluia, alleluia Wow! Superbe sortie.
Le reste, mais je suis emballée, emballée, se portée, mais c'est un petit bijou
C'est un petit bijou
Quelle dommage ! Parce que la sortie, elle était très originale.
Mais non, mais non, je vais tout ! C'était sublime la descente
Mais non, mais non, je vais tout ! C'était sublime la descente
Pour moi, ils m'ont emballée sur la deuxième note
Pour moi, ils m'ont emballée sur la deuxième note
Ça a été magique
Splendide.
Enfin, quoique, on va voir parce que c'est bon
Oh, et que c'est beau ! Fluide et léger
J'en parle même pas, c'était de toute beauté
Il n'y a pas de recette
C'était rare aujourd'hui.
Ah là là oui absolument
On a surtout en tête le dessert
Évidemment on pense à ce dessert formidable, mon préféré
Ah oui, mon préféré aussi.
Oui mais c'était de l'autre côté
Ils ont été extraordinaires
C'est énorme
C'est incroyable
C'est incroyable
C'est très impressionnant.
C'est incroyable la longévité
Franchement, un immense bravo.
Très beau
Et c'était très surprenant
C'était autre chose
Moi j'aime bien
Alors le porté, c'est bof, c'est plus que parfait
C'est exceptionnel.
C'est exceptionnel
C'est très sympa
Donc c'est très très très intelligent de leur part
Une chimie incroyable
Ils ont été aussi beaucoup belissés en décembre
Et c'est excellent
C'est exceptionnel ce qu'ils viennent de réaliser
C'était exceptionnel
Je précise que c'est rare.
Ce sont ces premières choses qu'elle dit, vivre une aventure incroyable et sauvage
C'est la perfection
Elle est parfaite
Il est parfait
Maintenant c'est bon pour Lorraine ça
Vraiment je la trouve éblouissante
C'est très très bien
Ah je l'avais aimé.
C'est vraiment super intéressant de les suivre avec vous.
n'aime pas du tout d'ailleurs
Mais on a l'impression qu'elle s'admire tellement dans ce programme.
Faites-moi plaisir
Oui, un doux.
C'est tellement bien, c'est tellement parfait
On est dans un voyage partagé
Elle emmènera avec elle tous ses souvenirs.
C'est gentil
C'est parfait
ça c'est fantastique, fantastique
Là pour le coup on va tous savoir, c'est vraiment très bien
Oui, là, les images que l'on vient de voir, c'est magnifique
Et c'est magnifique
J'ai beaucoup aimé leur proposition
J'ai beaucoup aimé leur proposition
Franchement je suis ébahie par ce sans faute pour moi.
Ça donne un parfum
Ça donne un parfum
Ça donne un parfum
Ça donne un parfum
Ça donne un parfum
Ça donne un parfum
C'est ce qui se passe
Oh, bien! Quelle détente! C'est vraiment parfait ce qu'elle nous présente.
Ah oui, vous l'avez vu là, hein ? Un car, un bon bon car
Ça, ça nous cloue le bec
Ça, ça nous cloue le bec
Vraiment, c'est incroyable
Qu'un seul mot magnifique
Je serais très généreuse
Je serais très généreuse

Tests de stabilité

In [ ]:
# Main words of current model themes

reference = set()
for topic_id in topic_model.get_topics():
    if topic_id == -1:
        continue
    words = [w for w, _ in topic_model.get_topic(topic_id)[:10]]
    reference.add(tuple(sorted(words)))
reference

{('1',
  '8',
  'attention',
  'bonsoir',
  'fantastique',
  'ok',
  'oui',
  'oui oui',
  'oui thème',
  'thème'),
 ('100',
  '2ème',
  '2ème note',
  'monte',
  'monter',
  'note',
  'notes',
  'score',
  'scoret',
  'scorez'),
 ('102', '102 55', '1m75', '46', '55', '62', '64', '70', '92', 'mesure'),
 ('2',
  '23',
  'attention',
  'bascule',
  'famille',
  'imagine',
  'maxime',
  'oui',
  'parfait',
  'suspense'),
 ('2024',
  'champion',
  'champion monde',
  'championnat',
  'championnat europe',
  'championnats',
  'championnats europe',
  'europe',
  'monde',
  'titre'),
 ('2e',
  'classement',
  'instant',
  'place',
  'place provisoire',
  'podium',
  'podium provisoire',
  'prennent',
  'provisoire',
  'tête'),
 ('3',
  '3 4',
  '4',
  '4 tours',
  'demi',
  'tour',
  'tour tours',
  'tours',
  'tours demi',
  'tours tours'),
 ('4',
  'maximum',
  'niveau',
  'niveau 4',
  'niveau maximum',
  'niveau technique',
  'niveaux',
  'technique',
  'technique niveau',
  'techniques'),
 ('5',
  '5 points',
  'bonus',
  'bonus malus',
  'donner',
  'juges',
  'jury',
  'malus',
  'points',
  'élément'),
 ('60',
  '71',
  'battent',
  'battu',
  'meilleur',
  'meilleur score',
  'record',
  'saison',
  'score',
  'score saison'),
 ('accord',
  'complètement',
  'oui',
  'oui complètement',
  'oui oui',
  'oui raison',
  'oui sûr',
  'pieds',
  'suite',
  'sûr'),
 ('acrobatie',
  'acrobaties',
  'acrobatique',
  'acrobatiques',
  'niveau',
  'niveau maximum',
  'pirouette',
  'pirouettes',
  'pirouettes niveau',
  'série'),
 ('adore',
  'emballée',
  'exceptionnel',
  'incroyable',
  'magnifique',
  'mignon',
  'oui',
  'parfait',
  'super',
  'vraiment'),
 ('aime vraiment',
  'combat',
  'dégage',
  'exemple résilience',
  'puissance',
  'résilience',
  'sensibilité',
  'vraiment extraordinaire',
  'élégance',
  'énergie'),
 ('air',
  'axel',
  'combinaison',
  'petit',
  'points',
  'rotation',
  'saut',
  'sauts',
  'technique',
  'triple'),
 ('ambiance',
  'calme',
  'prendre',
  'prendre tête',
  'pression',
  'senti',
  'sentis',
  'serré',
  'serré serré',
  'tendu'),
 ('amodio',
  'entraîne',
  'entraînement',
  'entraînements',
  'entraînent',
  'entraîneur',
  'entraîneurs',
  'florent',
  'heures',
  'sport'),
 ('annick',
  'annick nathalie',
  'annick pensé',
  'chat',
  'nathalie',
  'nathalie nathalie',
  'nathalie trouvé',
  'pensez',
  'pensé',
  'trouvé'),
 ('annick',
  'entraînement',
  'erreur',
  'expérience',
  'gauchère',
  'hier',
  'hier entraînement',
  'note',
  'particularité',
  'technique'),
 ('appel',
  'appel vidéo',
  'appels',
  'appels vidéo',
  'arrivée',
  'arrivée parfaite',
  'besoin',
  'parfaite',
  'propre',
  'vidéo'),
 ('argent',
  'bronze',
  'derniers jeux',
  'jeux',
  'jeux olympiques',
  'médaille',
  'médaille bronze',
  'olympique',
  'olympiques',
  'or'),
 ('arrière',
  'blessée',
  'bras',
  'bras air',
  'changement',
  'changement position',
  'jambe',
  'main',
  'pied',
  'position'),
 ('artistique',
  'artistiquement',
  'artistiques',
  'choix',
  'choix artistique',
  'créativité',
  'côté',
  'osent',
  'plan',
  'proposition artistique'),
 ('attention',
  'attention attention',
  'ex',
  'impression',
  'inspiration',
  'intérêt',
  'oui élément',
  'parlais heure',
  'petit détail',
  'source'),
 ('axe',
  'axel',
  'axel double',
  'double',
  'double axel',
  'lame',
  'rotation',
  'souhaite',
  'triple',
  'triple axel'),
 ('aïe',
  'aïe aïe',
  'contents',
  'déçue',
  'extrêmement',
  'heureux',
  'joie',
  'raison',
  'sourire',
  'émue'),
 ('beaudry',
  'cizeron',
  'fournier',
  'geoffrey',
  'guillaume',
  'guillaume cizeron',
  'guillaume laurence',
  'laurence',
  'laurence fournier',
  'laurence guillaume'),
 ('boléro',
  'choix',
  'chorégraphie',
  'chorégraphique',
  'danse',
  'film',
  'musical',
  'musique',
  'patiner',
  'rythme'),
 ('boucle',
  'boucle piquée',
  'flip',
  'piqué',
  'piquée',
  'salco',
  'triple',
  'triple boucle',
  'triple flip',
  'triple salco'),
 ('canada',
  'canada france',
  'france',
  'france tête',
  'géorgie',
  'instant',
  'italie',
  'japon',
  'place',
  'tête'),
 ('canada',
  'canadiens',
  'couple',
  'couples',
  'ensemble',
  'japon',
  'japonais',
  'parents',
  'performance',
  'vraiment'),
 ('championne',
  'championne monde',
  'kajiyama',
  'kaori',
  'kaori sakamoto',
  'monde',
  'sakamoto',
  'triple championne',
  'yuma',
  'yuma kajiyama'),
 ('chute',
  'chute chute',
  'chutes',
  'considéré',
  'double peine',
  'déduction',
  'déduction chute',
  'peine',
  'point',
  'point déduction'),
 ('compétition',
  'compétition compétition',
  'event',
  'finale',
  'team',
  'team event',
  'épreuve',
  'épreuve équipe',
  'épreuves',
  'équipe'),
 ('copie',
  'copie danse',
  'danse',
  'danse glace',
  'feu',
  'glace',
  'glace couple',
  'glace française',
  'patinoire',
  'patinoire milan'),
 ('court',
  'libre',
  'libre programme',
  'meilleur programme',
  'programme',
  'programme court',
  'programme libre',
  'programme programme',
  'programme voir',
  'programmes'),
 ('ensemble',
  'patinage',
  'patinent',
  'patiner',
  'patineur',
  'patineurs',
  'patineuse',
  'patineuses',
  'patiné',
  'qualité'),
 ('etats',
  'etats unis',
  'tiennent',
  'tête',
  'unis',
  'unis france',
  'unis tiennent',
  'unis tête',
  'états',
  'états unis'),
 ('lancé',
  'lutz',
  'parallèle',
  'quad',
  'quadruple',
  'quadruples',
  'saut',
  'saut lancé',
  'sauts',
  'triple'),
 ('message',
  'montrer',
  'montrera',
  'oui',
  'regarde',
  'regardons',
  'suspense',
  'sûre',
  'verra',
  'voir')}

On run 10 fois le même modèle à 80% du corpus pour voir la stabilité des thèmes

In [ ]:
from sklearn.utils import resample
from collections import Counter

# List of words for each topic for each model
all_topics_words = []

# Number of runs
nb_iter = 10

for i in range(nb_iter):

    # First, resample 80% of docs
    sample = resample(docs, n_samples=int(len(docs) * 0.8), random_state=i)

    # Same model specification
    model = BERTopic(
    embedding_model=embedding_model,
    vectorizer_model=vectorizer_model,
    hdbscan_model=hdbscan_model,
    language="french",
    calculate_probabilities=True,
    verbose=True,
    seed_topic_list=seed    
)
    model.fit(sample)
    
    # Top 10 words per topic
    top_words = set()
    for topic_id in model.get_topics():
        if topic_id == -1:
            continue
        words = [w for w, _ in model.get_topic(topic_id)[:10]]
        top_words.add(tuple(sorted(words)))
    
    all_topics_words.append(top_words)


# Jaccard similarity index
def jaccard(t1, t2):
    s1, s2 = set(t1), set(t2)
    return len(s1 & s2) / len(s1 | s2)

# Topic stability
"""
Measures similarity between reference topic and topics found in other runs.

Thresholds for stability are determined by Jaccard index (threshold) and number of occurences (min_run)
"""
def is_stable(topic, all_runs, threshold=0.2, min_runs=7):
    count = 0
    for run_topics in all_runs:
        if any(jaccard(topic, t) >= threshold for t in run_topics):
            count += 1
    return count >= min_runs


stable_topics = [t for t in reference if is_stable(t, all_topics_words)]

print(f"Thèmes stables (≥7 runs sur 10) : {len(stable_topics)}")
for t in stable_topics:
    print(t)

In [19]:
from sklearn.utils import resample
from collections import Counter
from sklearn.cluster import HDBSCAN
from bertopic import BERTopic
from bertopic.cluster import BaseCluster
from sentence_transformers import SentenceTransformer
from sklearn.feature_extraction.text import CountVectorizer
# Modèle de référence sur le corpus complet
ref_model = BERTopic(
    embedding_model=embedding_model,
    vectorizer_model=CountVectorizer(stop_words=STOPWORDS, ngram_range=(1,2), min_df=2, token_pattern=r"\b(?!\w*[A-Z])\w+\b"),
    hdbscan_model=SklearnHDBSCAN(min_cluster_size=50, min_samples=10, cluster_selection_epsilon=0.1, cluster_selection_method='leaf'),
    language="french",
    calculate_probabilities=True,
    verbose=True,
    seed_topic_list=seed
)
ref_model.fit(df["text"])

reference = set()
for topic_id in ref_model.get_topics():
    if topic_id == -1:
        continue
    words = [w for w, _ in ref_model.get_topic(topic_id)[:10]]  # 10 mots
    reference.add(tuple(sorted(words)))

# Bootstrap sur sous-échantillons
all_topics_words = []
for i in range(10):
    sample = resample(df["text"], n_samples=int(len(df["text"]) * 0.8), random_state=i)
    
    model_i = BERTopic(
        embedding_model=embedding_model,
        vectorizer_model=CountVectorizer(stop_words=STOPWORDS, ngram_range=(1,2), min_df=2, token_pattern=r"\b(?!\w*[A-Z])\w+\b"),
        hdbscan_model=SklearnHDBSCAN(min_cluster_size=50, min_samples=10, cluster_selection_epsilon=0.1, cluster_selection_method='leaf'),
        language="french",
        calculate_probabilities=True,
        verbose=True,
    )
    model_i.fit(sample)
    
    top_words = set()
    for topic_id in model_i.get_topics():
        if topic_id == -1:
            continue
        words = [w for w, _ in model_i.get_topic(topic_id)[:10]]  # 10 mots
        top_words.add(tuple(sorted(words)))
    
    all_topics_words.append(top_words)

# Faire un Jaccard entre chaque run et compter les thèmes stables
def jaccard(t1, t2):
    s1, s2 = set(t1), set(t2)
    return len(s1 & s2) / len(s1 | s2)

def is_stable(topic, all_runs, threshold=0.3, min_runs=7):
    count = 0
    for run_topics in all_runs:
        if any(jaccard(topic, t) >= threshold for t in run_topics):
            count += 1
    return count >= min_runs
# Stabilité : thèmes du modèle référence présents dans ≥7 runs bootstrap
stable_topics = [t for t in reference if is_stable(t, all_topics_words, threshold=0.2, min_runs=7)]
print(f"Thèmes stables (≥7 runs sur 10) : {len(stable_topics)}")
for t in stable_topics:
    print(t)

2026-03-21 18:29:08,986 - BERTopic - Embedding - Transforming documents to embeddings.
Batches:   0%|          | 0/246 [00:00<?, ?it/s]

Batches: 100%|██████████| 246/246 [00:13<00:00, 18.09it/s]
2026-03-21 18:29:22,682 - BERTopic - Embedding - Completed ✓
2026-03-21 18:29:22,683 - BERTopic - Guided - Find embeddings highly related to seeded topics.
Batches: 100%|██████████| 1/1 [00:00<00:00, 102.34it/s]
2026-03-21 18:29:22,835 - BERTopic - Guided - Completed ✓
2026-03-21 18:29:22,846 - BERTopic - Dimensionality - Fitting the dimensionality reduction algorithm
2026-03-21 18:30:06,666 - BERTopic - Dimensionality - Completed ✓
2026-03-21 18:30:06,671 - BERTopic - Cluster - Start clustering the reduced embeddings
2026-03-21 18:30:07,171 - BERTopic - Cluster - Completed ✓
2026-03-21 18:30:07,181 - BERTopic - Representation - Fine-tuning topics using representation models.
2026-03-21 18:30:07,427 - BERTopic - Representation - Completed ✓
2026-03-21 18:30:07,707 - BERTopic - Embedding - Transforming documents to embeddings.
Batches: 100%|██████████| 197/197 [00:10<00:00, 18.02it/s]
2026-03-21 18:30:18,706 - BERTopic - Embedding - Completed ✓
2026-03-21 18:30:18,707 - BERTopic - Dimensionality - Fitting the dimensionality reduction algorithm
2026-03-21 18:30:54,646 - BERTopic - Dimensionality - Completed ✓
2026-03-21 18:30:54,648 - BERTopic - Cluster - Start clustering the reduced embeddings
2026-03-21 18:30:54,947 - BERTopic - Cluster - Completed ✓
2026-03-21 18:30:54,953 - BERTopic - Representation - Fine-tuning topics using representation models.
2026-03-21 18:30:55,119 - BERTopic - Representation - Completed ✓
2026-03-21 18:30:55,316 - BERTopic - Embedding - Transforming documents to embeddings.
Batches: 100%|██████████| 197/197 [00:11<00:00, 17.72it/s]
2026-03-21 18:31:06,506 - BERTopic - Embedding - Completed ✓
2026-03-21 18:31:06,508 - BERTopic - Dimensionality - Fitting the dimensionality reduction algorithm
2026-03-21 18:31:52,169 - BERTopic - Dimensionality - Completed ✓
2026-03-21 18:31:52,172 - BERTopic - Cluster - Start clustering the reduced embeddings
2026-03-21 18:31:52,488 - BERTopic - Cluster - Completed ✓
2026-03-21 18:31:52,494 - BERTopic - Representation - Fine-tuning topics using representation models.
2026-03-21 18:31:52,645 - BERTopic - Representation - Completed ✓
2026-03-21 18:31:52,830 - BERTopic - Embedding - Transforming documents to embeddings.
Batches: 100%|██████████| 197/197 [00:11<00:00, 17.47it/s]
2026-03-21 18:32:04,183 - BERTopic - Embedding - Completed ✓
2026-03-21 18:32:04,184 - BERTopic - Dimensionality - Fitting the dimensionality reduction algorithm
2026-03-21 18:32:43,975 - BERTopic - Dimensionality - Completed ✓
2026-03-21 18:32:43,977 - BERTopic - Cluster - Start clustering the reduced embeddings
2026-03-21 18:32:44,292 - BERTopic - Cluster - Completed ✓
2026-03-21 18:32:44,300 - BERTopic - Representation - Fine-tuning topics using representation models.
2026-03-21 18:32:44,478 - BERTopic - Representation - Completed ✓
2026-03-21 18:32:44,720 - BERTopic - Embedding - Transforming documents to embeddings.
Batches: 100%|██████████| 197/197 [00:10<00:00, 18.82it/s]
2026-03-21 18:32:55,270 - BERTopic - Embedding - Completed ✓
2026-03-21 18:32:55,272 - BERTopic - Dimensionality - Fitting the dimensionality reduction algorithm
2026-03-21 18:33:33,346 - BERTopic - Dimensionality - Completed ✓
2026-03-21 18:33:33,349 - BERTopic - Cluster - Start clustering the reduced embeddings
2026-03-21 18:33:33,657 - BERTopic - Cluster - Completed ✓
2026-03-21 18:33:33,665 - BERTopic - Representation - Fine-tuning topics using representation models.
2026-03-21 18:33:33,852 - BERTopic - Representation - Completed ✓
2026-03-21 18:33:34,088 - BERTopic - Embedding - Transforming documents to embeddings.
Batches: 100%|██████████| 197/197 [00:10<00:00, 19.50it/s]
2026-03-21 18:33:44,275 - BERTopic - Embedding - Completed ✓
2026-03-21 18:33:44,276 - BERTopic - Dimensionality - Fitting the dimensionality reduction algorithm
2026-03-21 18:34:20,447 - BERTopic - Dimensionality - Completed ✓
2026-03-21 18:34:20,452 - BERTopic - Cluster - Start clustering the reduced embeddings
2026-03-21 18:34:20,774 - BERTopic - Cluster - Completed ✓
2026-03-21 18:34:20,781 - BERTopic - Representation - Fine-tuning topics using representation models.
2026-03-21 18:34:20,984 - BERTopic - Representation - Completed ✓
2026-03-21 18:34:21,203 - BERTopic - Embedding - Transforming documents to embeddings.
Batches: 100%|██████████| 197/197 [00:09<00:00, 20.08it/s]
2026-03-21 18:34:31,078 - BERTopic - Embedding - Completed ✓
2026-03-21 18:34:31,080 - BERTopic - Dimensionality - Fitting the dimensionality reduction algorithm
2026-03-21 18:35:12,872 - BERTopic - Dimensionality - Completed ✓
2026-03-21 18:35:12,876 - BERTopic - Cluster - Start clustering the reduced embeddings
2026-03-21 18:35:13,175 - BERTopic - Cluster - Completed ✓
2026-03-21 18:35:13,184 - BERTopic - Representation - Fine-tuning topics using representation models.
2026-03-21 18:35:13,346 - BERTopic - Representation - Completed ✓
2026-03-21 18:35:13,549 - BERTopic - Embedding - Transforming documents to embeddings.
Batches: 100%|██████████| 197/197 [00:09<00:00, 20.86it/s]
2026-03-21 18:35:23,059 - BERTopic - Embedding - Completed ✓
2026-03-21 18:35:23,060 - BERTopic - Dimensionality - Fitting the dimensionality reduction algorithm
2026-03-21 18:35:58,649 - BERTopic - Dimensionality - Completed ✓
2026-03-21 18:35:58,652 - BERTopic - Cluster - Start clustering the reduced embeddings
2026-03-21 18:35:58,940 - BERTopic - Cluster - Completed ✓
2026-03-21 18:35:58,946 - BERTopic - Representation - Fine-tuning topics using representation models.
2026-03-21 18:35:59,100 - BERTopic - Representation - Completed ✓
2026-03-21 18:35:59,312 - BERTopic - Embedding - Transforming documents to embeddings.
Batches: 100%|██████████| 197/197 [00:09<00:00, 21.75it/s]
2026-03-21 18:36:08,434 - BERTopic - Embedding - Completed ✓
2026-03-21 18:36:08,435 - BERTopic - Dimensionality - Fitting the dimensionality reduction algorithm
2026-03-21 18:36:43,679 - BERTopic - Dimensionality - Completed ✓
2026-03-21 18:36:43,683 - BERTopic - Cluster - Start clustering the reduced embeddings
2026-03-21 18:36:43,987 - BERTopic - Cluster - Completed ✓
2026-03-21 18:36:43,998 - BERTopic - Representation - Fine-tuning topics using representation models.
2026-03-21 18:36:44,177 - BERTopic - Representation - Completed ✓
2026-03-21 18:36:44,404 - BERTopic - Embedding - Transforming documents to embeddings.
Batches: 100%|██████████| 197/197 [00:08<00:00, 21.96it/s]
2026-03-21 18:36:53,445 - BERTopic - Embedding - Completed ✓
2026-03-21 18:36:53,446 - BERTopic - Dimensionality - Fitting the dimensionality reduction algorithm
2026-03-21 18:37:31,979 - BERTopic - Dimensionality - Completed ✓
2026-03-21 18:37:31,981 - BERTopic - Cluster - Start clustering the reduced embeddings
2026-03-21 18:37:32,267 - BERTopic - Cluster - Completed ✓
2026-03-21 18:37:32,275 - BERTopic - Representation - Fine-tuning topics using representation models.
2026-03-21 18:37:32,441 - BERTopic - Representation - Completed ✓
2026-03-21 18:37:32,644 - BERTopic - Embedding - Transforming documents to embeddings.
Batches: 100%|██████████| 197/197 [00:09<00:00, 21.76it/s]
2026-03-21 18:37:41,772 - BERTopic - Embedding - Completed ✓
2026-03-21 18:37:41,773 - BERTopic - Dimensionality - Fitting the dimensionality reduction algorithm
2026-03-21 18:38:15,672 - BERTopic - Dimensionality - Completed ✓
2026-03-21 18:38:15,677 - BERTopic - Cluster - Start clustering the reduced embeddings
2026-03-21 18:38:15,974 - BERTopic - Cluster - Completed ✓
2026-03-21 18:38:15,980 - BERTopic - Representation - Fine-tuning topics using representation models.
2026-03-21 18:38:16,140 - BERTopic - Representation - Completed ✓

Thèmes stables (≥7 runs sur 10) : 20
('canada', 'canada france', 'chine pologne', 'france', 'france tête', 'instant', 'italie', 'place', 'rappelle france', 'tête')
('2ème', '2ème note', 'monte', 'monter', 'note', 'notes', 'score', 'scoret', 'scorez', 'énormément')
('60', '71', 'battent', 'battu', 'meilleur', 'meilleur score', 'record', 'saison', 'score', 'score saison')
('classement', 'instant', 'place', 'place provisoire', 'podium', 'podium provisoire', 'prennent', 'provisoire', 'sato', 'tête')
('4', 'annick niveau', 'maximum', 'niveau', 'niveau 4', 'niveau maximum', 'niveau technique', 'niveaux', 'technique', 'éléments')
('90', 'années', 'chorégraphe', 'chorégraphie', 'chorégraphies', 'chorégraphique', 'dance', 'danse', 'rythme', 'rythme danse')
('5', '5 points', 'bonus', 'bonus malus', 'donner', 'juges', 'jury', 'malus', 'points', 'élément')
('championne', 'championne monde', 'japon', 'kajiyama', 'kaori', 'kaori sakamoto', 'monde', 'sakamoto', 'yuma', 'yuma kajiyama')
('combinaison', 'combinaison sauts', 'lancé', 'lancés', 'parallèle', 'saut', 'saut lancé', 'sauts', 'sauts lancés', 'triple')
('court', 'libre', 'libre programme', 'meilleur programme', 'programme', 'programme court', 'programme libre', 'programme voir', 'programmes', 'vraiment')
('amodio', 'entraîne', 'entraînement', 'entraînent', 'entraîneur', 'entraîneurs', 'florent', 'répéter', 'sport', 'échauffer')
('air', 'arrivée', 'axel', 'combinaison', 'petit', 'points', 'saut', 'sauts', 'technique', 'triple')
('lutz', 'lutz triple', 'prévu', 'quad', 'quadruple', 'quadruple lutz', 'quadruples', 'quads', 'triple', 'triple lutz')
('ensemble', 'patinage', 'patinent', 'patiner', 'patineur', 'patineurs', 'patineuse', 'patineuses', 'patiné', 'qualité')
('boucle', 'flip', 'piqué', 'piquée', 'quadruple', 'salco', 'triple', 'triple boucle', 'triple flip', 'triple salco')
('bronze', 'champion', 'champion monde', 'champions', 'monde', 'monde titre', 'médaille', 'médaille bronze', 'or', 'titre')
('annick', 'annick pensé', 'marie', 'nathalie', 'nathalie nathalie', 'nathalie trouvé', 'pensez', 'pensé', 'question', 'œil')
('copie danse', 'danse', 'danse glace', 'feu', 'glace', 'glace couple', 'glace programme', 'milieu', 'patinoire', 'référence')
('beaudry', 'cizeron', 'fournier', 'geoffrey', 'guillaume', 'guillaume cizeron', 'guillaume laurence', 'laurence', 'laurence fournier', 'laurence guillaume')
('air', 'arrière', 'blessée', 'bras', 'bras air', 'change position', 'jambe', 'pied', 'position', 'rotation')

In [9]:
# Install dependencies if needed
# pip install bertopic sentence-transformers umap-learn hdbscan

from bertopic import BERTopic
from sentence_transformers import SentenceTransformer
from sklearn.feature_extraction.text import CountVectorizer
from umap import UMAP
from sklearn.cluster import HDBSCAN
from bertopic.cluster import BaseCluster

class SklearnHDBSCAN(BaseCluster):
    def __init__(self, *args, **kwargs):
        self.model = HDBSCAN(*args, **kwargs)
    
    def fit(self, X):
        self.model.fit(X)
        self.labels_ = self.model.labels_
        return self
    
    def fit_predict(self, X):
        self.labels_ = self.model.fit_predict(X)
        return self.labels_
hdbscan_model = SklearnHDBSCAN(
    min_cluster_size=50,      # bigger = fewer, larger topics
    min_samples=10,            # higher = more conservative clustering
    cluster_selection_epsilon=0.1,  # merge nearby clusters
    cluster_selection_method='leaf' # fewer, more specific clusters
)

# Load CamemBERT embedding model
embedding_model = SentenceTransformer("dangvantuan/sentence-camembert-base", device="cuda")

STOPWORDS = [x.strip() for x in open('stopwords.txt').readlines()]

# Vectorizer for topic representation
vectorizer_model = CountVectorizer(
    stop_words=STOPWORDS,
    ngram_range=(1,2),
    min_df=2
)
#umap_model = UMAP(n_neighbors=15, n_components=5, min_dist=0.0, random_state=42)
seed =  [
["émotion","larme","ému","joie","tristesse"],
["famille","parents","ami", "personnel", "conjoint"]]
""",
["attaque","montée","effort","énergie","relance","sprint"],        # tactique
["médaille","podium","victoire","champion","record","victoire","classement","premier","deuxième","troisième"],              # résultats
["bravo","chapeau","incroyable","monstrueux","magnifique","énorme"],        # admiration
["tir","cible","pénalité","debout","couché","faute"],                      # technique
["âge","ans","carrière","champion du monde","olympique","saison"],
["rapide","forme","expérience","solide","rapide","bon"],          # profil athlète
["devant","revient","prend la tête","écart","seconde", "temps","tour","intermédiaire","course","piste"] 
]"""
# Build BERTopic model
topic_model = BERTopic(
    embedding_model=embedding_model,
    vectorizer_model=vectorizer_model,
    hdbscan_model=hdbscan_model,
    language="french",
    calculate_probabilities=True,
    verbose=True,
    seed_topic_list=seed    
)

# Fit the model
topics, probs = topic_model.fit_transform(df["text"])

# Show discovered topics
print(topic_model.get_topic_info())

# Show keywords for a specific topic
print(topic_model.get_topic(0))

# Visualize topics
topic_model.visualize_topics()

# Visualize topic hierarchy
topic_model.visualize_hierarchy()

#keybertopic, extrait phrases saillantes
#tester lda
#virer phrases nulles et refaire tourner
#pas virer -1 sauf si faible échantillon et checker
#checker si semi-superviser pour trouver thèmes

Loading weights: 100%|██████████| 199/199 [00:00<00:00, 3988.47it/s]
CamembertModel LOAD REPORT from: dangvantuan/sentence-camembert-base
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
2026-03-21 18:17:45,341 - BERTopic - Embedding - Transforming documents to embeddings.
Batches: 100%|██████████| 246/246 [00:12<00:00, 19.01it/s]
2026-03-21 18:17:58,369 - BERTopic - Embedding - Completed ✓
2026-03-21 18:17:58,370 - BERTopic - Guided - Find embeddings highly related to seeded topics.
Batches: 100%|██████████| 1/1 [00:00<00:00, 16.60it/s]
2026-03-21 18:17:58,642 - BERTopic - Guided - Completed ✓
2026-03-21 18:17:58,643 - BERTopic - Dimensionality - Fitting the dimensionality reduction algorithm
2026-03-21 18:18:42,881 - BERTopic - Dimensionality - Completed ✓
2026-03-21 18:18:42,882 - BERTopic - Cluster - Start clustering the reduced embeddings
2026-03-21 18:18:43,334 - BERTopic - Cluster - Completed ✓
2026-03-21 18:18:43,341 - BERTopic - Representation - Fine-tuning topics using representation models.
2026-03-21 18:18:43,514 - BERTopic - Representation - Completed ✓

    Topic  Count                                               Name  \
0      -1   3249             -1_programme_vraiment_points_technique
1       0    283                       0_axel_bras_position_spirale
2       1    282                  1_couple_couples_canadiens_canada
3       2    280            2_patinage_patineur_patineurs_patineuse
4       3    260       3_incroyable_parfait_magnifique_exceptionnel
5       4    256                         4_aïe_aïe aïe_joie_sourire
6       5    209                 5_chorégraphie_musique_danse_choix
7       6    181                        6_vitesse_triple_petit_saut
8       7    175                        7_voir_sûre_regardons_verra
9       8    169         8_provisoire_place_place provisoire_podium
10      9    136                 9_oui oui_oui_sûr_oui complètement
11     10    133               10_glace_danse glace_danse_patinoire
12     11    132                 11_limite_parfait_attention_maxime
13     12    125                     12_saut_sauts_lancé_saut lancé
14     13    122                        13_juges_bonus_malus_niveau
15     14    118                        14_triple_boucle_piqué_flip
16     15    105             15_laurence_guillaume_cizeron_fournier
17     16    104                        16_note_scorez_monter_notes
18     17    103                   17_unis_etats_etats unis_géorgie
19     18    100         18_nathalie_pensé_nathalie nathalie_annick
20     19     98      19_programme_libre_programmes_programme libre
21     20     93  20_technique_niveau technique_niveau_annick ni...
22     21     92              21_artistique_public_show_artistiques
23     22     91                        22_france_canada_place_tête
24     23     78                  23_lutz_quadruple_quadruples_quad
25     24     75    24_entraîne_entraînement_entraîneurs_entraînent
26     25     75     25_difficile_dur_compliqué_difficile programme
27     26     66            26_médaille_monde_bronze_champion monde
28     27     61                    27_chute_déduction_chutes_peine
29     28     59      28_pirouettes_pirouette_niveau_niveau maximum
30     29     59          29_sakamoto_kaori sakamoto_kaori_kajiyama
31     30     58                             30_2024_2025_2023_2022
32     31     57             31_compétition_épreuve_team_team event
33     32     56       32_olympiques_jeux olympiques_jeux_olympique
34     33     55        33_score_meilleur score_score saison_saison
35     34     54                            34_55_mesure_102 55_102
36     35     54          35_annick_gauchère_hier entraînement_hier
37     36     54                        36_ok_bonsoir_oui_attention
38     37     53                     37_patiner_patine_film_musique
39     38     50                   38_russes_anastasia_russie_russe

                                       Representation  \
0   [programme, vraiment, points, technique, kevin...
1   [axel, bras, position, spirale, triple axel, r...
2   [couple, couples, canadiens, canada, japon, en...
3   [patinage, patineur, patineurs, patineuse, pat...
4   [incroyable, parfait, magnifique, exceptionnel...
5   [aïe, aïe aïe, joie, sourire, déçue, émue, rai...
6   [chorégraphie, musique, danse, choix, interpré...
7   [vitesse, triple, petit, saut, risque, combina...
8   [voir, sûre, regardons, verra, montrer, messag...
9   [provisoire, place, place provisoire, podium, ...
10  [oui oui, oui, sûr, oui complètement, oui sûr,...
11  [glace, danse glace, danse, patinoire, feu, ré...
12  [limite, parfait, attention, maxime, interdit,...
13  [saut, sauts, lancé, saut lancé, parallèle, la...
14  [juges, bonus, malus, niveau, bonus malus, max...
15  [triple, boucle, piqué, flip, triple flip, tri...
16  [laurence, guillaume, cizeron, fournier, guill...
17  [note, scorez, monter, notes, scoret, 2ème not...
18  [unis, etats, etats unis, géorgie, états unis,...
19  [nathalie, pensé, nathalie nathalie, annick, m...
20  [programme, libre, programmes, programme libre...
21  [technique, niveau technique, niveau, annick n...
22  [artistique, public, show, artistiques, artist...
23  [france, canada, place, tête, france tête, jap...
24  [lutz, quadruple, quadruples, quad, triple lut...
25  [entraîne, entraînement, entraîneurs, entraîne...
26  [difficile, dur, compliqué, difficile programm...
27  [médaille, monde, bronze, champion monde, or, ...
28  [chute, déduction, chutes, peine, double peine...
29  [pirouettes, pirouette, niveau, niveau maximum...
30  [sakamoto, kaori sakamoto, kaori, kajiyama, yu...
31  [2024, 2025, 2023, 2022, monde, champion monde...
32  [compétition, épreuve, team, team event, event...
33  [olympiques, jeux olympiques, jeux, olympique,...
34  [score, meilleur score, score saison, saison, ...
35  [55, mesure, 102 55, 102, 46, 62, 64, 92, 70, 05]
36  [annick, gauchère, hier entraînement, hier, er...
37  [ok, bonsoir, oui, attention, oui oui, malheur...
38  [patiner, patine, film, musique, soir, patine ...
39  [russes, anastasia, russie, russe, nationalité...

                                  Representative_Docs
0   [J'ai trouvé des éléments de très très bonne f...
1   [Le triple axel., Et du triple axel, Une émett...
2   [C'est un couple très charismatique, Non mais ...
3   [C'est un patineur que je suis régulièrement, ...
4   [C'est incroyable, C'est incroyable., Ce qui e...
5    [Aïe aïe aïe, K.O, Aïe aïe aïe., Aïe, aïe, aïe.]
6   [Évidemment, il y a un message dans cette chor...
7   [Quelle vitesse et la prise de risque, Quelle ...
8   [Maintenant, on va voir, On va le voir, Celle-...
9   [Septième place provisoire, Troisième place pr...
10  [Oui, oui, tout à fait, Oui, oui ça va, Oui, m...
11  [en danse sur glace, Alors voilà, après la dan...
12  [Parfois limite, Limite également, Un limite é...
13  [L'autre saut lancé., Un saut lancé, c'est ça,...
14  [C'est les bonus et les malus, C'est à dire de...
15  [C'est un triple boucle., Et quadruple boucle ...
16  [Derrière, Guillaume Cizeron, Laurence Fournie...
17  [Alors la note, Sur la deuxième note, ça va êt...
18  [Etats-Unis, 1, Etats-Unis, 1, que les Etats-U...
19  [Nathalie, c'est votre domaine ça., Sixième, N...
20  [Et à Dan, il y a Wim Fa, qui a fait un progra...
21  [Annick au niveau de la technique, Au niveau t...
22  [C'est artistique, À l'artistique, en haut, Tr...
23  [Va-t-on rester en tête de cette compétition a...
24  [Ah le voilà, le voilà, ce lutz, Le voilà le l...
25  [Elle s'entraîne à Vaujany avec Florent Amodio...
26  [C'est tellement difficile à faire, Et ça, c'e...
27  [Le pays qui aura le plus de points aura la mé...
28  [Et il y a pas de chute., Il y a en plus une c...
29  [-"Desynchronisations sur la pirouette." .., L...
30  [Et la dernière a passé, Kaori Sakamoto, le Ja...
31  [Elle a passé 4 mois sans compétition pendant ...
32  [Cette compétition va se dérouler en deux phas...
33  [Ils participent à leur premier Jeux Olympique...
34  [Le meilleur score de la saison eux aussi comm...
35  [parce que je peux vous assurer qu'entre 102, ...
36  [Et moi aussi Annick, Je pense à Annick, Alors...
37                                       [OK, OK, OK]
38  [Quatrième après le programme court, il patine...
39  [Mais en fait, comme beaucoup de patineurs et ...
[('axel', np.float64(0.07682324774111426)), ('bras', np.float64(0.0718786862269786)), ('position', np.float64(0.05733107868203186)), ('spirale', np.float64(0.05394877093663437)), ('triple axel', np.float64(0.05230809387837144)), ('rotation', np.float64(0.04818247143541753)), ('arrière', np.float64(0.045576926357477614)), ('acrobatie', np.float64(0.033251596787276703)), ('main', np.float64(0.030618127408273944)), ('triple', np.float64(0.028598819663740314))]

In [11]:
t = pd.DataFrame({
    "text": df['text'],
    "topic": topics
    #"topic_prob": probs.max(axis=1)  # max probability per text
})

In [ ]:
t = pd.DataFrame({
    "text": df['text'],
    "topic": topics
    #"topic_prob": probs.max(axis=1)  # max probability per text
})
t["topic"].value_counts()

topic
-1     3249
 0      283
 1      282
 2      280
 3      260
 4      256
 5      209
 6      181
 7      175
 8      169
 9      136
 10     133
 11     132
 12     125
 13     122
 14     118
 15     105
 16     104
 17     103
 18     100
 19      98
 20      93
 21      92
 22      91
 23      78
 24      75
 25      75
 26      66
 27      61
 29      59
 28      59
 30      58
 31      57
 32      56
 33      55
 34      54
 36      54
 35      54
 37      53
 38      50
Name: count, dtype: int64

In [67]:
topic_model.get_topic(4,full=True)

False

In [ ]:
#1 : 4, 17, 18 retirés
#2 : 

t = pd.DataFrame({
    "text": df['text'],
    "topic": topics
    #"topic_prob": probs.max(axis=1)  # max probability per text
})
t["topic"].value_counts()
for k in t[t["topic"]==4]["text"] : 
    print(k)

On est très fiers
Vu leur joie, effectivement
Oui, soyez contents.
Il fait des investissements dans l'immobilier
Ils sont contents
Et d'ailleurs, ça me dépensait à quelque chose
Regardez le visage du partenaire, il souffre
Il doit mourir.
Annick, vous avez été émue par ce programme ?
Oui, j'ai été émue incontestablement
Elle décompense, elle dit.
Tout paraît tellement simple.
Annick, vous en avez pensé quoi ? Mais c'est compliqué pour la France.
Elle ne l'est pas du tout, du tout
Il a une patate, ça se transmet, on sent qu'il aime ça
Mais ce n'est pas ce qu'on nous souhaite, le pot
Et le petit sourire
Kajiyama qui avait remporté la médaille de bronze au dernier championnat du monde et était extrêmement extrêmement déçu
Il disait voilà j'ai loupé parce que j'ai plus confiance en moi et finalement vous voyez c'est pas le cas
Il a ça dans le sang
Il a raté sa vie, c'est tout
Très fâchée, c'est un grand mot.
Et effectivement j'étais surprise, mais pas complètement, puisque ce n'est pas la première fois que ça lui arrive
Ils sont contents, ils ont raison de l'être
Qui laisse tout derrière lui, sans se retourner.
Ça fait mal.
On voit Ilya Malinink qui est venu supporter son équipe
Marjorie Lajoie, Zachary Laga, habité par cette histoire et cette destinée de Rudolf Nouriev devant le sourire de Marie-France Dubreuil.
C'est une personne très investie dans l'autisme puisque elle a un frère autiste.
J'ai l'impression qu'ils ne sont pas tout à fait contents de ce qu'ils ont fait
C'est l'aile Chris, il est décédé il y a cinq ans et elle a toujours cette attention envers son frère dans ce moment là.
elle a vécu des hauts et des bas et elle est là
Elle est française et je pense que ça lui tenait à cœur aussi
Vraiment on a eu de l'émotion pendant tout ce programme ?
J'ai beaucoup d'émotions, je pense que c'est lié aussi à la joie que leur a procuré cette médaille de bronze par équipe il y a quelques jours sur cette même glace
Je suis très positive pour cette performance
Alors, je suis désolée
un hommage célèbre peintre
On parlera à Elle Piper, il y a trois ans, qui luttait contre un cancer
Beaucoup d'émotions de la part des Canadiens, de leur entraîneur, de tout le monde
Piper, Guiless, en pleurs
Ça fait super plaisir de les voir comme ça.
Et ça, forcément, en tant que Français, on est contents qu'elle existe, cette marche.
Je suis tellement émue par ce programme que...
Je suis tellement émue par ce programme
On ne peut pas vous aider, mais moi j'y crois
Ce moment est terrible
La fierté de toute une nation et plus encore
La couleur des barrières
Regardez si elle vous dit son visage
Je me réjouis de voir une jeune génération, je vous en parlais
À Détroit
Non mais vraiment, c'est pas une blague
Après lui, il avait un peu ça dans le sang
Ils ont toujours de l'humour, du second degré
Elle est extrêmement drôle
Elle est drôle, vraiment
Elle est très très drôle
Je vous ai rattrapé, je vous ai rattrapé, parce que j'ai besoin de vous, alors je vous Après lui, je le trouve extraordinaire
Et je rejoins Annie
Et je pense qu'on l'a fait avec fierté ce soir.
Ils peuvent être fiers
Ils sont déçus, bien sûr
En fait, quoi qu'il arrive maintenant, il ne faut ni s'alarmer, ni s'enthousiasmer s'ils sont un ou s'ils sont deux, nos Français
Elle est plus faible que celle de nos Français
Elle a toujours pas de nouvelles de la prof
Je n'ose pas vous en parler.
Mais là, c'est vraiment dommage parce qu'elle a été courageuse
Franchement, on avait l'impression de revivre ce merveilleux film qui est l'histoire d'une femme qui perd son mari dans un accident d'avion
Qui n'a pas pleuré sur ce film ? Nathalie, vous avez failli pleurer là.
Mais j'ai trouvé ça extrêmement émouvant
C'est un petit peu fleur bleue, mais c'est l'amour qui résiste à tout au-delà de la mort
Et là, elle va nous faire partir dans la vie en rose, l'hymne à l'amour, et non, je ne regrette rien, interprété par Patricia Cass.
Pour la plage c'est assez pratique
Il a beaucoup d'humour
Quand on n'a jamais fait de foot, je peux vous assurer que ça ne vous parle pas
Aïe aïe aïe c'est bas c'est bas, oh la la c'est bas.
Nathalie ? Non mais c'est extrêmement grave pour lui ce qui vient de se passer, surtout qu'on est vraiment, on est passé d'une émotion
On était tellement heureux pour lui
Donc vraiment, on était mais folle de joie
Cette patinoire est remplie, alors qu'on s'est souvent étonnés du fait qu'il y ait encore beaucoup de place libre
Parfois, il passe à côté
Moi je suis très déçue pour lui parce que la stratégie je ne la comprends pas non plus mais elle est peut-être liée à son état de forme.
Ça ne veut pas dire que c'est mort
Il est hyper content, regardez-le
Aïe aïe aïe, K.O
Alors là, ça va être pour lui une catastrophe
Oui, avec Kevin et Mos Kevin, on vous a senti extrêmement heureux, soulagés, on a vu quelques larmes même à la fin de ce programme
Du coup, les larmes, c'est parce que j'ai vu ma mère dans les gradins tout en haut
Mais je suis allé le chercher, le programme, je suis trop fier de moi
C'est que du bonheur, je suis trop content
Je suis allé le chercher, non, je suis trop content, tellement fier
C'est trop bien, je suis trop content.
J'ai tout donné pour représenter mon pays, mes valeurs et d'où je viens et qui je suis donc non franchement je suis trop je suis trop heureux
Ça a plu au public
Ah ouais je suis trop content
En tout cas j'en connais trois en tribune qui ont été très fiers
Il a livré à ses ouvertements tous ses sentiments, toutes ses impressions et comment il avait réussi à se reconstruire
C'est un grand sensible, il arrive bien à l'exprimer, que ce soit avec sa gestuelle sur la glace ou avec ses mots, quand il doit analyser ses ressentis et les raisons parfois de son mal-être
Mais comme on l'a entendu à l'instant aussi, de ce qui fait son bonheur, évidemment le nôtre.
C'est forcément une déception pour le Japonais
Je suis sans voix
Il y a tant d'émotions, tant d'énergie
Lui aussi a un sac dans le sang
Le choix de poche
C'est peu, c'est peu ! 103,07
à ce moment là du match il est super important mais à la fin au final il compte pas donc donc voilà c'est ça change rien ça change rien l'issue du match oui c'est frustrant mais je suis hyper fière du groupe je pense qu'aujourd'hui on a montré qui on était je pense qu'on a montré nos valeurs j'espère que les gens ont pu le ont pu le voir en tout cas nous dans le groupe voilà on a switché par rapport à hier et je pense qu'on peut on peut être fier de ça je suis très frustré je suis très déçu parce que je pense qu'on aurait pu aller chercher le match au moins une prolongation mais à la fois je suis hyper fier de la force de caractère qu'on a fait preuve et voilà ça n'a pas payé on joue contre une équipe du japon qui a aussi l'expérience de ces moments là de ces matchs là et mais on les a fait douter pendant pendant 55 minutes 55 minutes et Je pense que ça, personne ne nous l'enlèvera
Ça fait plaisir et c'est un soulagement de la voir dans cet état de forme après sa grave blessure
Vous avez un petit espoir
Oh la la la, mais ça c'est une catastrophe
Je suis assez surprise de telles erreurs
Bonjour Pavel
Mais à part ça, je suis très heureux d'être là et de notre performance d'aujourd'hui.
Je suis enchantée sur la technique
Je suis enchantée
Le phare, un peu comme métaphore pour guider les gens face aux aléas de la vie
Je le regrette parce que j'ai vraiment aimé
Quelle dommage !
Vous avez vu la coach extrêmement émue aussi de cette performance
Regardez son petit sourire, elle est contente d'elle, elle a raison
C'est sympa, elle est heureuse, elle a raison.
Beaucoup de déchets.
Elle nous disait qu'elle était très détendue et ravie d'être là
Et alors elle a eu un sourire de béatitude une fois qu'elle a passé ces deux éléments techniques
Elle a souri tout l'eau, c'était merveilleux
Hier elle nous disait qu'elle était très défendue et ravie d'être là
Et alors, elle a eu un sourire de béatitude une fois qu'elle a passé Ces deux éléments techniques, elle a souri tout l'eau, c'était merveilleux
Le royaillon peut rugir de plaisir, rugir de plaisir plutôt
Ça ne s'hérite pas
Elle est lumineuse et c'est surtout un bel être humain qui a toujours sourire et qui vous répond avec beaucoup de gentillesse.
C'est la parole de la mort.
Oh la la la pauvre
Ah là là, ça c'est une catastrophe
Oui, vraiment, ça c'est catastrophique pour eux
Je ne sais pas comment le dire autrement, mais là, j'ai la gorge qui se serre
C'est très très bouleversant.
Un sac pour l'Ukraine
On a un oiseau de feu qui évoque la lutte entre le bien et le mal
Moi j'ai espoir pour le Canadien.
Et c'est ce qui lui est arrivé
On peut s'imaginer que c'est anodin mais ça ne l'est pas du tout
On connaît tous son sens artistique et sa capacité à émouvoir
C'est l'émotion à l'état pur
C'est une manière aussi de s'exprimer, d'exprimer le rêve, la marginalité
C'était assez empreinte de mélancolie et de liberté sur la fin avec beaucoup d'emphase.
Il pleure
Il a eu le mal du pays
Il a bien raison parce qu'on n'a rien à perdre
C'est exactement ce qui lui est arrivé
Vraiment, quelle déception
Je suis tellement, mais tellement déçue
C'est vrai que je suis complètement déçue pour lui
Aïe, aïe, aïe.
On est désolé
Je suis désolée pour lui, parce que je sais combien ce moment est rare dans une carrière d'athlète
Il est d'une tristesse infinie
Ça nous brise le cœur de le voir comme ça
Quelle surprise
Je n'en reviens pas.
Mireille Scheidorf
Quelle tristesse.
Et vraiment, alors, excusez-moi, mais obligé d'avoir une pensée pour Donnie Sten, le dernier médaillé olympique kazakh
Souvenez-vous, médaillé de bronze aux Jeux Olympiques de 2014 à Sochi qui a été sauvagement assassiné alors qu'il n'avait que 25 ans.
C'était une catastrophe
Je n'en reviens pas
Et cela ne nous arrange pas du tout
Voilà la combinaison en deuxième partie, elle sourit, elle a raison
Il a râlé
Je me suis fâchée qu'une fois
Nina Petrukina pour l'Estonie c'est un exemple de résilience
Oui, mais c'est bien ça son histoire, la pauvre.
Pour vous donner des nouvelles, c'est assez incroyable et effroyable ce qui lui est arrivé à Roman Kostomarov
La transition n'est pas facile
Ah là là là là ça c'est terrible
Devant le regard de son frère à droite
Elle a annoncé
C'est très poétique, très doux
Écoutez ce public l'acclamer, elle disait justement qu'elle était très étonnée de l'accueil qu'elle a reçu ici
Elle a eu un sourire, mais c'est incroyable
Elle avait pris sa retraite à 16 ans, elle avait décidé de profiter de la vie et puis elle est revenue à 20 ans et elle est hyper contente et nous aussi pour elle.
Et bien elle sourit tranquille.
Elle explose pas de joie même
Non, je ne regrette rien et un hymne à l'amour sublime pour un adieu olympique et, certainement, sans aucun doute, un dernier frisson.
Très touchante
Quelle richesse ! Alors, le bleu, regardez, c'est tellement émouvant
C'est petit, c'est petit.
J'ai peur qu'elle soit déçue.
Elle est un petit peu déçue Kaori Sakamoto, elle était là pour l'or
C'est tout ce qu'on lui souhaitait
Elle pleure, Kaoris, Akamoto.
Non, non, c'est pas dit que ça soit une déception.
Ça faisait le mal au cœur d'avoir comme ça
Non mais attendez, elle peut pleurer de joie aussi, on ne pleure pas que de tristesse
Amina et Kaye ont ce qu'elle a plein de joie
Elle est heureuse
Rassurez-vous, personne n'est mort.
Je suis enchantée sur la technique
Je suis enchantée
Le phare, un peu comme métaphore pour guider les gens face aux aléas de la vie
Alors ça doit vous dire évidemment quelque chose
Je le regrette parce que j'ai vraiment aimé
Un mélange entre la jeunesse d'Elli et l'expérience d'Annie à 34 ans
Il a investi dans l'immobilier
Il y a le Canada au milieu, mais il reste encore de belles nations et de beaux couples.
Vous avez vu la coach extrêmement émue aussi de cette performance
C'est sympa, elle est heureuse, elle a raison.
Pour moi le bleu c'est l'équipe de France mais je ne sais pas pourquoi.
C'est toujours le couple canadien Lya Perera et Trent Mitchell
Une version, vous allez le voir, extrêmement émouvante
Il lui rend hommage
Pas forcément utile, mais c'est tellement dur de trouver le bon partenaire
La fille est à 3,50 m du sol
Mais j'étais très contente d'être un fondant de rôle.
Pour ce magnifique combat entre la bête et le matador.
Vraiment, il est effondré.
Vous imaginez la déception
Et là, je suis sidérée de cette erreur, comme il doit s'en vouloir
En vrai, je suis en train de m'en vouloir
Et là, c'est une grosse déception pour ces doubles champions du monde
C'est dans un mouchoir de poche
Je n'allais pas être déçue
Je ne sais pas ce que ça veut dire, sauvage.
Elle est super contente
C'est un petit peu moins propre.
Il y a encore quelques années c'était un tout petit bout, plutôt introverti, plutôt timide
Et ça c'est beaucoup, beaucoup de fois perdu
Mais là, aïe aïe aïe
Aïe aïe aïe.
Ça se ressent, elle a l'air pleine de vie, pleine de, je ne sais pas, pleine de joie
l'espère pour elle
Et elle a un peu la sang, hein
C'est quand même dans un mouchoir de poche
Un tout petit mouchoir de poche
Tout petit poche honnête.
Time to say goodbye.
Mais attention, contrairement à ce qu'on pourrait croire, c'est pas une chanson qui parle simplement de partir, mais surtout de partir avec la personne que l'on aime
Elle est déçue
Merci de croire en moi
Elle a fait de la dépression, de la santé mentale son véritable combat
Et ça va être catastrophique comme on l'a vu avec Shibas, comme on l'a vu avec..
Oh moi je pourrais pleurer avec elle vraiment
J'ai mal vu
On est tous si tellement dégés
Normalement on dit que quand elle est en larmes, la pauvre, elle fait tellement de peine à voir.
C'est trop d'émotions là ! On va finir dans quel état ?
Merci à toutes les trois, on vous souhaite une excellente fin de soirée.
Et alors, ce qui est important pour nous, la délégation française, c'est qu'elle n'était pas présente à Pékin en 2022
C'est un acteur et chanteur d'Hong Kong
Et on commence à ressentir de l'émotion projetée dans le public.
ça compte aussi l'expression du visage d'Anthalie.
D'abord, ils sont heureux, ils ont raison
Vous avez un petit espoir.
Le roi Lyon peut rougir de plaisir, rougir de plaisir
Ça m'impressionne
Ça ne s'hérite pas, elle est dans une générosité
On vient avec beaucoup d'enthousiasme, beaucoup d'espoir,

In [28]:
mask = t[(t["topic"]!=4)&(t["topic"]!=17)&(t["topic"]!=18)]["text"]

In [29]:
d2 = d.merge(mask, on="text")

In [64]:
d2.merge(t,on="text")[d2.merge(t,on="text")["topic"]==18]

,Unnamed: 0,start,stop,text,main_speaker,main_g,audio_file,topic,topic_prob
498,398,4755.72,4757.72,C'est une belle histoire pour lui.,SPEAKER_05,female,BI_wav.wav,18,1.00000
588,515,6473.40,6476.36,"Il y a des leçons à tirer, malgré la déception...",SPEAKER_11,male,BI_wav.wav,18,1.00000
605,11,424.80,440.80,Juste le temps peut-être de saluer dans la raq...,SPEAKER_11,male,BIF_wav.wav,18,0.14816
937,342,4304.68,4312.68,C'est les belles histoires des jeux. Les belle...,SPEAKER_06,female,BIF_wav.wav,18,1.00000
948,353,4474.68,4496.68,"Oui, c'est vraiment... Bien évidemment, Trista...",SPEAKER_11,male,BIF_wav.wav,18,1.00000
1005,56,814.00,820.00,C'est long une Olympiade Avec toutes les émoti...,SPEAKER_04,male,BMH_wav.wav,18,1.00000
1041,97,1299.90,1307.90,La santé c'est le plus important. Elle peut êt...,SPEAKER_03,male,BMH_wav.wav,18,1.00000
1048,104,1369.90,1373.90,"Quand on connaît ses qualités, ça fend le cœur...",SPEAKER_04,female,BMH_wav.wav,18,1.00000
1621,173,1963.72,1972.56,"Va se laisser prendre par les émotions. Allez,...",SPEAKER_01,male,BMF_wav.wav,18,1.00000
1954,246,2668.36,2672.36,Oh les belles émotions.,SPEAKER_04,music,BMF_wav.wav,18,1.00000
2062,98,1244.00,1245.20,Il y a des sourires.,SPEAKER_09,male,SCR2_wav.wav,18,1.00000
2077,113,1420.24,1425.24,Et on prend le temps de savourer. Et nous auss...,SPEAKER_11,male,SCR2_wav.wav,18,1.00000

In [48]:
topic_model.get_topic(-1)

[('tir', np.float64(0.019705384158766548)),
 ('course', np.float64(0.01810100205230608)),
 ('julia', np.float64(0.016166922702569482)),
 ('secondes', np.float64(0.01581559885555621)),
 ('petit', np.float64(0.015216028128888991)),
 ('vraiment', np.float64(0.014750896397992897)),
 ('faut', np.float64(0.014264980364740047)),
 ('allez', np.float64(0.014103260774615873)),
 ('20', np.float64(0.01389915649281138)),
 ('aller', np.float64(0.013604787866193726))]

In [ ]:
from sentence_transformers import SentenceTransformer
from sklearn.metrics.pairwise import cosine_similarity

model = SentenceTransformer("dangvantuan/sentence-camembert-base")


sentence_embeddings = model.encode(d2["text"])
theme_embeddings = model.encode(themes)

sim = cosine_similarity(sentence_embeddings, theme_embeddings)
labels = sim.argmax(axis=1)

Loading weights: 100%|██████████| 199/199 [00:00<00:00, 2362.30it/s]
CamembertModel LOAD REPORT from: dangvantuan/sentence-camembert-base
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

In [136]:
d2["labels"]=labels

In [147]:
d2[d2["labels"]==8]["text"]

0       En endroit, on est parti pour vivre encore un ...
3       Moi je vais vous donner les numéros de Dossard...
4       Ouais l'équivalent à peu près de deux tours et...
7       Il a un rôle important dans cette équipe. Donc...
9       On discutait hier justement dans la reconnaiss...
                              ...
1427    Et on prend le temps de savourer. Et nous auss...
1428    Elle vient de passer derrière le pas de tir. E...
1434    Simon l'a dit, Simon Fourcade, l'entraîneur de...
1440    La Suède, qui revient à 3 secondes dès Nord-Vé...
1441    Ça va pas le mettre en confiance pour le début...
Name: text, Length: 444, dtype: object

In [131]:
themes = []
for i in seed : 
    themes.append(" ".join(i))
themes

['émotion larme ému joie triste histoire hommage',
 'famille parents ami personnelle',
 'attaque montée effort énergie relance sprint',
 'médaille podium victoire champion record victoire classement premier deuxième troisième',
 'bravo chapeau incroyable monstrueux magnifique énorme',
 'tir cible pénalité debout couché faute',
 'âge ans carrière champion du monde olympique saison',
 'rapide forme expérience solide rapide bon',
 'devant revient prend la tête écart seconde temps tour intermédiaire course piste']

In [65]:
test = topic.merge(d, on="text")

In [67]:
test[(test["topic"]==10)|(test["topic"]==15)]

,text,topic,topic_prob,start,stop,main_speaker,main_g,audio_file
8,Pour vous en dire un petit peu plus sur la pis...,10,1.000000,289.60,345.80,SPEAKER_05,female,BI_wav.wav
9,On discutait hier justement dans la reconnaiss...,10,0.124827,345.80,356.40,SPEAKER_12,male,BI_wav.wav
11,Après c'est vrai que cette année il y a des st...,15,1.000000,374.20,386.60,SPEAKER_05,female,BI_wav.wav
13,"C'est un athlète solide, le jeune Suisse qui p...",15,0.238053,421.20,434.20,SPEAKER_12,male,BI_wav.wav
25,C'est un athlète qui a énormément d'expérience...,15,0.219121,604.20,622.20,SPEAKER_12,male,BI_wav.wav
26,"Cette année, il est un tout petit peu moins bo...",15,1.000000,622.20,634.20,SPEAKER_05,female,BI_wav.wav
28,"Fabien, c'est vraiment un skieur qui fait part...",15,1.000000,677.20,709.20,SPEAKER_05,female,BI_wav.wav
78,"Là, ça fait mal. On voit dans le regard qu'il ...",10,0.364798,1586.20,1595.20,SPEAKER_12,female,BI_wav.wav
93,On a l'impression qu'il y a les jambes qui tre...,10,1.000000,1724.20,1734.20,SPEAKER_05,female,BI_wav.wav
639,"Comme on l'avait dit pour le relais mixte, c'e...",10,0.152644,4025.84,4036.72,SPEAKER_05,female,BI_wav.wav
730,Complètement. C'est vrai que sur un individuel...,15,1.000000,4674.68,4727.28,SPEAKER_03,male,BI_wav.wav
754,Sur une piste exigeante où il faut sans cesse ...,10,1.000000,4900.40,4910.40,SPEAKER_12,male,BI_wav.wav
781,Un Boateng qui a été mais sacrément solide auj...,15,0.158726,5278.72,5290.12,SPEAKER_12,male,BI_wav.wav
783,Il lui a fallu une saison pour assimiler ce tr...,15,0.139592,5291.96,5312.84,SPEAKER_12,male,BI_wav.wav
786,"Olaq, oui, grand respect pour ce qu'il a pu fa...",15,1.000000,5577.64,5598.52,SPEAKER_04,male,BI_wav.wav
792,Comment avez-vous vécu cette course ? C'est un...,15,1.000000,5682.28,5750.04,SPEAKER_10,male,BI_wav.wav
794,"Écoutez, je fais un sport difficile. Pékin, ça...",15,1.000000,5756.48,5790.24,SPEAKER_10,male,BI_wav.wav
796,"Oui, je savais que... Avec l'expérience et la ...",15,1.000000,5793.48,5806.16,SPEAKER_10,male,BI_wav.wav
803,"Oui, avec des scies. On refait toutes les cour...",15,0.420427,5865.28,5900.56,SPEAKER_05,female,BI_wav.wav
813,C'est la révélation dans le sens où il a tenté...,15,0.187653,6146.16,6167.84,SPEAKER_12,male,BI_wav.wav
829,Oui. Je n'ai pas encore regardé les temps de s...,15,0.648638,6476.52,6512.36,SPEAKER_06,male,BI_wav.wav
839,C'est un format à part parce que c'est un form...,10,1.000000,210.80,236.80,SPEAKER_06,female,BIF_wav.wav
841,"Oui, il y aura toujours 4 tirs. On internera u...",10,1.000000,297.80,339.80,SPEAKER_10,male,BIF_wav.wav
842,"Oui, Alain, le stade d'hier, c'est une boucle,...",10,0.331937,339.80,378.80,SPEAKER_06,female,BIF_wav.wav
895,Lou après c'est sûr qu'elle a des grosses qual...,10,1.000000,1032.80,1062.80,SPEAKER_06,female,BIF_wav.wav
1032,"C'est dur ces individuels. Il faut tenir, il f...",10,0.340778,2667.48,2677.72,SPEAKER_06,female,BIF_wav.wav
1223,Après je peux vous dire que tous les efforts Q...,10,1.000000,392.00,412.00,SPEAKER_04,female,BMH_wav.wav
1225,La difficulté pour Fabien C'est qu'en fait com...,10,0.250248,430.00,450.00,SPEAKER_04,female,BMH_wav.wav
1232,Vous voyez là ça s'est vachement étiré Quand i...,10,0.510518,530.00,536.00,SPEAKER_04,male,BMH_wav.wav
1284,Ça va être compliqué pour Eric. On sent qu'il ...,10,0.529535,1080.90,1085.90,SPEAKER_04,female,BMH_wav.wav
1304,Là il n'est pas bien du tout déjà. Il se plain...,15,1.000000,1281.90,1299.90,SPEAKER_02,male,BMH_wav.wav
1362,Quentin derrière. Quentin est toujours costaud...,10,0.136500,1840.90,1855.90,SPEAKER_03,male,BMH_wav.wav
1410,"Quand on a ces qualités comme ça, d'être capab...",10,1.000000,2277.34,2285.02,SPEAKER_04,female,BMH_wav.wav
1507,35 ans sur sa piste à domicile. C'est un jubil...,10,0.327829,292.60,299.36,SPEAKER_02,male,BMF_wav.wav
1577,"Ca va partir. Selon les configurations du tir,...",10,0.308954,873.20,886.44,SPEAKER_04,male,BMF_wav.wav
1616,"La piste est difficile. Elle le sait, qu'il fa...",10,0.240924,1278.04,1286.40,SPEAKER_04,female,BMF_wav.wav
1650,Elles ont intérêt à partir. À ne pas laisser r...,10,0.255938,1598.32,1605.60,SPEAKER_04,female,BMF_wav.wav
1674,"L'enjeu, ça va être de ne pas penser aux résul...",10,0.609322,1856.40,1865.40,SPEAKER_04,female,BMF_wav.wav
1675,"Déposer le cerveau, mais garder le gros cœur. ...",10,1.000000,1865.56,1881.32,SPEAKER_01,male,BMF_wav.wav
1800,C'est pour ça que toutes les secondes d'avance...,10,1.000000,171.48,184.60,SPEAKER_11,male,SCR2_wav.wav
1818,Elle aura tout donné jusqu'au bout.,10,0.142104,398.28,400.04,SPEAKER_06,female,SCR2_wav.wav
1819,Il faut creuser les écarts. Il faut vraiment d...,10,0.452203,401.16,413.56,SPEAKER_10,male,SCR2_wav.wav
1835,Attention à Francis Caprus. On a l'impression ...,15,0.214445,621.60,635.76,SPEAKER_11,male,SCR2_wav.wav
1852,Je pense que ça sera compliqué pour eux d'espé...,15,1.000000,859.28,879.12,SPEAKER_06,female,SCR2_wav.wav